# Pandas met Fred
We gaan macro-economische data inlezen bij de FED in St. Louis: https://fred.stlouisfed.org/categories

In [1]:
! pip install pandas-datareader==0.10.0
! pip install yfinance

import yfinance as yf
import pandas as pd
import pandas_datareader.data as web
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from datetime import date

#Clear output
from google.colab import output
output.clear()

Alle libraries geinstalleerd, nu de data:

In [3]:
yf.pdr_override()

start = dt.datetime(2017,11,15)
end = dt.datetime(2022,12,15)

In [4]:
inflatie = web.get_data_fred('T10YIE', start, end) #inflatie
rente = web.get_data_fred('FEDFUNDS', start, end) #rente
graan = web.get_data_fred('PWHEAMTUSDM', start, end) #graan
koper = web.get_data_fred('PCOPPUSDM', start, end) #koperprijs
koffie = web.get_data_fred('WPU026301', start, end) #koffiebonen
hout = web.get_data_fred('WPU08', start, end) #hout
vlees = web.get_data_fred('PBEEFUSDM', start, end) #vleesprijs
zonnebloem = web.get_data_fred('PSUNOUSDM', start, end) #zonnebloemolie
wol = web.get_data_fred('PWOOLFUSDM', start, end) #wol
katoen = web.get_data_fred('PCOTTINDUSDM', start, end) #katoen
rubber = web.get_data_fred('PRUBBUSDM', start, end) #rubber
oil = web.get_data_yahoo('CL=F', start, end).tz_localize(None) #olie 
goud = web.get_data_yahoo('GC=F', start, end).tz_localize(None) #goud

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Even kijken hoe het eruit ziet:

In [5]:
hout.head()

            WPU08
DATE
2017-12-01  235.6
2018-01-01  237.3
2018-02-01  242.4
2018-03-01  244.7
2018-04-01  244.8

Of gaan we straks de regressie doen op de prijsveranderingen per dag:

In [ ]:
hout.pct_change()

               WPU08
DATE
2017-12-01       NaN
2018-01-01  0.007216
2018-02-01  0.021492
2018-03-01  0.009488
2018-04-01  0.000409
2018-05-01  0.020016
2018-06-01  0.013216
2018-07-01 -0.008696
2018-08-01 -0.018341
2018-09-01 -0.007717
2018-10-01 -0.018420
2018-11-01 -0.013344
2018-12-01  0.000845
2019-01-01  0.000422
2019-02-01  0.007598
2019-03-01 -0.001676
2019-04-01  0.002518
2019-05-01 -0.003349
2019-06-01 -0.009240
2019-07-01  0.002967
2019-08-01 -0.004649
2019-09-01  0.001699
2019-10-01 -0.002543
2019-11-01 -0.000850
2019-12-01  0.001701
2020-01-01  0.000849
2020-02-01  0.009758
2020-03-01  0.014706
2020-04-01 -0.020704
2020-05-01  0.005074
2020-06-01  0.023559
2020-07-01  0.029593
2020-08-01  0.057884
2020-09-01  0.077736
2020-10-01 -0.022409
2020-11-01 -0.045845
2020-12-01  0.031156
2021-01-01  0.064434
2021-02-01  0.026334
2021-03-01  0.039320
2021-04-01  0.045527
2021-05-01  0.097823
2021-06-01  0.007263
2021-07-01 -0.100643
2021-08-01 -0.072252
2021-09-01 -0.026090
2021-10-01  0.015852
2021-11-01  0.013858
2021-12-01  0.058076
2022-01-01  0.093632
2022-02-01  0.030674
2022-03-01  0.035923
2022-04-01 -0.044038
2022-05-01  0.006705
2022-06-01 -0.068441
2022-07-01 -0.007796
2022-08-01 -0.007526
2022-09-01 -0.019646
2022-10-01 -0.018630
2022-11-01 -0.014092

Sowieso toe te voegen aan deze tabellen: is dit een prijs per dag? In welke eenheid? Per m3 of liter of vat of ..

Afijn: eerst maar weer de portfolio-data inlezen:

In [ ]:
apple = web.get_data_yahoo('AAPL', start, end).tz_localize(None)
btc = web.get_data_yahoo('BTC-USD', start, end).tz_localize(None)
eth = web.get_data_yahoo('ETH-USD', start, end).tz_localize(None)
bond = web.get_data_yahoo('^TYX', start, end).tz_localize(None)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [ ]:
portfolio = pd.concat([apple, btc, eth, bond], axis=1)
portfolio = pd.concat([apple.add_suffix("_Apple"), btc.add_suffix("_Bitcoin"), eth.add_suffix("_Ethereum"),bond.add_suffix("_Bond")], axis=1)
portfolio_gefilterd = portfolio.loc[:, ["Close_Bitcoin", "Close_Ethereum", "Close_Bond", "Close_Apple"]]
nans_gevuld = portfolio_gefilterd.ffill()
nans_gevuld

            Close_Bitcoin  Close_Ethereum  Close_Bond  Close_Apple
Date
2017-11-15    7315.540039      333.356995       2.781    42.270000
2017-11-16    7871.689941      330.924011       2.806    42.775002
2017-11-17    7708.990234      332.394012       2.793    42.537498
2017-11-18    7790.149902      347.612000       2.793    42.537498
2017-11-19    8036.490234      354.385986       2.793    42.537498
...                   ...             ...         ...          ...
2022-12-10   17128.724609     1266.384155       3.549   142.160004
2022-12-11   17104.193359     1263.868530       3.549   142.160004
2022-12-12   17206.437500     1274.619019       3.576   144.490005
2022-12-13   17781.318359     1320.549194       3.528   145.470001
2022-12-14   17815.650391     1309.328735       3.539   143.210007

[1856 rows x 4 columns]

En nu het 'piece-de-resistance': beide tabellen samenvoegen:

In [ ]:
apt = pd.concat([nans_gevuld, hout], axis=1)
apt_fill = apt.ffill()
apt_fill.head(10)

            Close_Bitcoin  Close_Ethereum  Close_Bond  Close_Apple  WPU08
2017-11-15    7315.540039      333.356995       2.781    42.270000    NaN
2017-11-16    7871.689941      330.924011       2.806    42.775002    NaN
2017-11-17    7708.990234      332.394012       2.793    42.537498    NaN
2017-11-18    7790.149902      347.612000       2.793    42.537498    NaN
2017-11-19    8036.490234      354.385986       2.793    42.537498    NaN
2017-11-20    8200.639648      366.730011       2.793    42.494999    NaN
2017-11-21    8071.259766      360.401001       2.763    43.285000    NaN
2017-11-22    8253.549805      380.652008       2.746    43.740002    NaN
2017-11-23    8038.770020      410.165985       2.746    43.740002    NaN
2017-11-24    8253.690430      474.911011       2.762    43.742500    NaN

Nu alles omzetten naar prijsveranderingen:

In [ ]:
return_portfolio = apt_fill.pct_change()
return_portfolio.head(10)

            Close_Bitcoin  Close_Ethereum  Close_Bond  Close_Apple  WPU08
2017-11-15            NaN             NaN         NaN          NaN    NaN
2017-11-16       0.076023       -0.007298    0.008990     0.011947    NaN
2017-11-17      -0.020669        0.004442   -0.004633    -0.005552    NaN
2017-11-18       0.010528        0.045783    0.000000     0.000000    NaN
2017-11-19       0.031622        0.019487    0.000000     0.000000    NaN
2017-11-20       0.020426        0.034832    0.000000    -0.000999    NaN
2017-11-21      -0.015777       -0.017258   -0.010741     0.018590    NaN
2017-11-22       0.022585        0.056190   -0.006153     0.010512    NaN
2017-11-23      -0.026023        0.077535    0.000000     0.000000    NaN
2017-11-24       0.026735        0.157851    0.005827     0.000057    NaN

We zijn nu bijna waar we wezen willen: alle rijen en kolommen gevuld. Laatste schoonmaakactie: het verwijderen / filteren van alle overgebleven NaN's.<p>
Dit doen we door als startdatum een datum te kiezen waarbij voor ALLE producten koersdata aanwezig zijn.
We zoeken eerst deze datum:

In [ ]:
portfolio_regressie = return_portfolio.loc[return_portfolio.loc[:, "Close_Ethereum"] < 0, :]
portfolio_regressie

            Close_Bitcoin  Close_Ethereum  Close_Bond  Close_Apple  WPU08
2017-11-16       0.076023       -0.007298    0.008990     0.011947    NaN
2017-11-21      -0.015777       -0.017258   -0.010741     0.018590    NaN
2017-11-25       0.065090       -0.018182    0.000000     0.000000    NaN
2017-11-28       0.024490       -0.015516    0.000362    -0.005859    NaN
2017-11-29      -0.016919       -0.095959    0.018438    -0.020743    NaN
...                   ...             ...         ...          ...    ...
2022-12-05      -0.009087       -0.016075    0.015160    -0.007983    0.0
2022-12-07      -0.014124       -0.030839   -0.030656    -0.013785    0.0
2022-12-09      -0.005821       -0.013138    0.027207    -0.003435    0.0
2022-12-11      -0.001432       -0.001986    0.000000     0.000000    0.0
2022-12-14       0.001931       -0.008497    0.003118    -0.015536    0.0

[904 rows x 5 columns]

De datum die we zoeken is 17 november 2017. Deze datum kunnen we nu gebruiken als startdatum voor onze portfolio.

# Hoe kun je nog meer data samenvoegen?
Via een join, een append of een merge:

In [ ]:
nans_gevuld.join(hout)

            Close_Bitcoin  Close_Ethereum  Close_Bond  Close_Apple  WPU08
Date
2017-11-15    7315.540039      333.356995       2.781    42.270000    NaN
2017-11-16    7871.689941      330.924011       2.806    42.775002    NaN
2017-11-17    7708.990234      332.394012       2.793    42.537498    NaN
2017-11-18    7790.149902      347.612000       2.793    42.537498    NaN
2017-11-19    8036.490234      354.385986       2.793    42.537498    NaN
...                   ...             ...         ...          ...    ...
2022-12-10   17128.724609     1266.384155       3.549   142.160004    NaN
2022-12-11   17104.193359     1263.868530       3.549   142.160004    NaN
2022-12-12   17206.437500     1274.619019       3.576   144.490005    NaN
2022-12-13   17781.318359     1320.549194       3.528   145.470001    NaN
2022-12-14   17815.650391     1309.328735       3.539   143.210007    NaN

[1856 rows x 5 columns]

In [ ]:
nans_gevuld.append(hout)

            Close_Bitcoin  Close_Ethereum  Close_Bond  Close_Apple    WPU08
2017-11-15    7315.540039      333.356995       2.781    42.270000      NaN
2017-11-16    7871.689941      330.924011       2.806    42.775002      NaN
2017-11-17    7708.990234      332.394012       2.793    42.537498      NaN
2017-11-18    7790.149902      347.612000       2.793    42.537498      NaN
2017-11-19    8036.490234      354.385986       2.793    42.537498      NaN
...                   ...             ...         ...          ...      ...
2022-07-01            NaN             NaN         NaN          NaN  331.669
2022-08-01            NaN             NaN         NaN          NaN  329.173
2022-09-01            NaN             NaN         NaN          NaN  322.706
2022-10-01            NaN             NaN         NaN          NaN  316.694
2022-11-01            NaN             NaN         NaN          NaN  312.231

[1916 rows x 5 columns]

De append voegt alleen de maandelijkse houtprijzen toe, maar combineert deze niet met de bestaande data. Voor ons doel dus  niet bruikbaar.

In [ ]:
apt = pd.merge(nans_gevuld, hout, left_index=True, right_on='DATE')
apt = pd.merge(nans_gevuld, hout, left_index=True, right_index=True)
apt

            Close_Bitcoin  Close_Ethereum  Close_Bond  Close_Apple    WPU08
2017-12-01   10975.599609      466.540009       2.758    42.762501  235.600
2018-01-01   13657.200195      772.640991       2.739    42.307499  237.300
2018-02-01    9170.540039     1036.790039       3.005    41.945000  242.400
2018-03-01   10951.000000      872.200012       3.088    43.750000  244.700
2018-04-01    6844.229980      379.606995       2.972    41.945000  244.800
2018-05-01    9119.009766      673.612976       3.137    42.275002  249.700
2018-06-01    7541.450195      580.043030       3.046    47.560001  253.000
2018-07-01    6385.819824      453.917999       2.983    46.277500  250.800
2018-08-01    7624.910156      420.747009       3.127    50.375000  246.200
2018-09-01    7193.250000      295.341003       3.010    56.907501  244.300
2018-10-01    6589.620117      230.768005       3.232    56.814999  239.800
2018-11-01    6377.779785      198.871994       3.387    55.555000  236.600
2018-12-01    4214.671875      118.635559       3.311    44.645000  236.800
2019-01-01    3843.520020      140.819412       3.020    39.435001  236.900
2019-02-01    3487.945312      107.609787       3.032    41.630001  238.700
2019-03-01    3859.583740      136.443619       3.124    43.742500  238.300
2019-04-01    4158.183105      141.830322       2.890    47.810001  238.900
2019-05-01    5402.697266      160.818344       2.917    52.630001  238.100
2019-06-01    8564.016602      265.391266       2.583    43.767502  235.900
2019-07-01   10583.134766      293.641113       2.559    50.387501  236.600
2019-08-01   10399.668945      217.808441       2.441    52.107498  235.500
2019-09-01    9757.970703      171.629425       1.970    52.185001  235.900
2019-10-01    8343.276367      177.340424       2.105    56.147499  235.300
2019-11-01    9261.104492      183.969894       2.212    63.955002  235.100
2019-12-01    7424.292480      151.185730       2.202    66.812500  235.500
2020-01-01    7200.174316      130.802002       2.389    73.412498  235.700
2020-02-01    9392.875000      183.673950       2.015    77.377502  238.000
2020-03-01    8562.454102      218.970596       1.671    68.339996  241.500
2020-04-01    6606.776367      135.634552       1.289    60.227501  236.500
2020-05-01    8864.766602      214.219101       1.278    72.267502  237.700
2020-06-01   10167.268555      246.991760       1.455    80.462502  243.300
2020-07-01    9228.325195      231.113419       1.433    91.027496  250.500
2020-08-01   11759.592773      385.199707       1.198   106.260002  265.000
2020-09-01   11970.478516      477.051910       1.425   134.179993  285.600
2020-10-01   10619.452148      353.205902       1.454   116.790001  279.200
2020-11-01   13737.109375      396.358185       1.640   108.860001  266.400
2020-12-01   18802.998047      587.324158       1.676   122.720001  274.700
2021-01-01   29374.152344      730.367554       1.646   132.690002  292.400
2021-02-01   33537.175781     1369.040527       1.847   134.139999  300.100
2021-03-01   49631.242188     1564.707642       2.220   127.790001  311.900
2021-04-01   59095.808594     1977.276855       2.340   123.000000  326.100
2021-05-01   57828.050781     2945.892822       2.301   131.460007  358.000
2021-06-01   36684.925781     2633.518311       2.296   124.279999  360.600
2021-07-01   33572.117188     2113.605469       2.086   137.270004  324.308
2021-08-01   39974.894531     2561.852051       1.897   145.860001  300.876
2021-09-01   48847.027344     3834.828125       1.919   152.509995  293.026
2021-10-01   48116.941406     3307.516113       2.058   142.649994  297.671
2021-11-01   61004.406250     4324.626953       1.969   148.960007  301.796
2021-12-01   57229.828125     4586.990234       1.778   164.770004  319.323
2022-01-01   47686.812500     3769.697021       1.905   177.570007  349.222
2022-02-01   38743.273438     2792.117188       2.124   174.610001  359.934
2022-03-01   44354.636719     2972.485107       2.104   163.199997  372.864
2022-04-01   46281.644531     3449.552246       2.424   174.309998  356.444
2022-05-01   38469.093750     2827.756104       2.947   157.649994  358.834
2022-06-01   29799.080078     1823.569336       3.076   148.710007  334.275
2022-07-01   19269.367188     1059.767334       3.116   138.929993  331.669
2022-08-01   23314.199219     1635.195801       2.925   161.509995  329.173
2022-09-01   20127.140625     1586.176758       3.374   157.960007  322.706
2022-10-01   19312.095703     1311.644409       3.765   138.199997  316.694
2022-11-01   20485.273438     1579.704590       4.124   150.649994  312.231

Keurig alles gevuld ..  maar we houden maar 116 rijen over? Rara hoe kan dit?
Omdat de hout-tabel maar 130 rijen heeft!

In [ ]:
apt = pd.merge(nans_gevuld, hout, how='outer', left_index=True, right_index=True)
apt

            Close_Bitcoin  Close_Ethereum  Close_Bond  Close_Apple  WPU08
2017-11-15    7315.540039      333.356995       2.781    42.270000    NaN
2017-11-16    7871.689941      330.924011       2.806    42.775002    NaN
2017-11-17    7708.990234      332.394012       2.793    42.537498    NaN
2017-11-18    7790.149902      347.612000       2.793    42.537498    NaN
2017-11-19    8036.490234      354.385986       2.793    42.537498    NaN
...                   ...             ...         ...          ...    ...
2022-12-10   17128.724609     1266.384155       3.549   142.160004    NaN
2022-12-11   17104.193359     1263.868530       3.549   142.160004    NaN
2022-12-12   17206.437500     1274.619019       3.576   144.490005    NaN
2022-12-13   17781.318359     1320.549194       3.528   145.470001    NaN
2022-12-14   17815.650391     1309.328735       3.539   143.210007    NaN

[1856 rows x 5 columns]

Ergo: als we gaan samenvoegen, moeten we eerst de ontbrekende waarden in de kolommen aanvullen met forward_fill. <br>
Kunnen we maandelijkse / jaarlijkse data op dagbasis aanvullen? Ja: zie hierboven.