In [ ]:
install.packages("tidyverse")
install.packages("zoo")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
library(tidyverse)
library(zoo)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   0.3.5
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.4.1
✔ readr   2.1.3      ✔ forcats 0.5.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

# Hoofdstuk 11 - Data Import (& Export)

We gaan een aantal manieren oefenen waarmee je data kunt inlezen:<br>
- CSV-bestanden<br>
- Excel-bestanden<br>
- Database-bestanden<br>
- SPSS-bestanden<br>
- XML-bestanden<br>

# CSV-bestanden
We zoeken eerst een mooi csv-bestand op internet:<br>
https://www.stats.govt.nz/large-datasets/csv-files-for-download/,<br> 
en lezen het vervolgens in:

In [ ]:
#csv_url <- "http://s3.amazonaws.com/assets.datacamp.com/production/course_1561/datasets/chickwts.csv"
csv_url <- "https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2021-financial-year-provisional/Download-data/annual-enterprise-survey-2021-financial-year-provisional-csv.csv"

csv_data <- read.csv(csv_url)
#csv_data <- read.csv("annual-enterprise-survey-2021-financial-year-provisional-csv.csv")
head(csv_data)

  Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC
1 2021 Level 1                     99999                All industries
2 2021 Level 1                     99999                All industries
3 2021 Level 1                     99999                All industries
4 2021 Level 1                     99999                All industries
5 2021 Level 1                     99999                All industries
6 2021 Level 1                     99999                All industries
  Units              Variable_code
1 Dollars (millions) H01
2 Dollars (millions) H04
3 Dollars (millions) H05
4 Dollars (millions) H07
5 Dollars (millions) H08
6 Dollars (millions) H09
  Variable_name                                   Variable_category     Value
1 Total income                                    Financial performance 757,504
2 Sales, government funding, grants and subsidies Financial performance 674,890
3 Interest, dividends and donations               Financial performance 49,593
4 Non-operating income                            Financial performance 33,020
5 Total expenditure                               Financial performance 654,404
6 Interest and donations                          Financial performance 26,138
  Industry_code_ANZSIC06
1 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
2 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
3 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
4 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
5 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
6 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)

# Intermezzo: hoofdstuk 10 - Tibbles
We maken er een [tibble](hthttps://r4ds.had.co.nz/tibbles.htmltps://) van:

In [ ]:
data <- as_tibble(csv_data)
data

      Year Industry_aggregation_NZSIOC Industry_code_NZSIOC
1     2021 Level 1                     99999
2     2021 Level 1                     99999
3     2021 Level 1                     99999
4     2021 Level 1                     99999
5     2021 Level 1                     99999
6     2021 Level 1                     99999
7     2021 Level 1                     99999
8     2021 Level 1                     99999
9     2021 Level 1                     99999
10    2021 Level 1                     99999
11    2021 Level 1                     99999
12    2021 Level 1                     99999
13    2021 Level 1                     99999
14    2021 Level 1                     99999
15    2021 Level 1                     99999
16    2021 Level 1                     99999
17    2021 Level 1                     99999
18    2021 Level 1                     99999
19    2021 Level 1                     99999
20    2021 Level 1                     99999
21    2021 Level 1                     99999
22    2021 Level 1                     99999
23    2021 Level 1                     99999
24    2021 Level 1                     99999
25    2021 Level 1                     99999
26    2021 Level 1                     99999
27    2021 Level 1                     99999
28    2021 Level 1                     99999
29    2021 Level 1                     99999
30    2021 Level 1                     99999
⋮     ⋮    ⋮                           ⋮
41686 2013 Level 3                     ZZ11
41687 2013 Level 3                     ZZ11
41688 2013 Level 3                     ZZ11
41689 2013 Level 3                     ZZ11
41690 2013 Level 3                     ZZ11
41691 2013 Level 3                     ZZ11
41692 2013 Level 3                     ZZ11
41693 2013 Level 3                     ZZ11
41694 2013 Level 3                     ZZ11
41695 2013 Level 3                     ZZ11
41696 2013 Level 3                     ZZ11
41697 2013 Level 3                     ZZ11
41698 2013 Level 3                     ZZ11
41699 2013 Level 3                     ZZ11
41700 2013 Level 3                     ZZ11
41701 2013 Level 3                     ZZ11
41702 2013 Level 3                     ZZ11
41703 2013 Level 3                     ZZ11
41704 2013 Level 3                     ZZ11
41705 2013 Level 3                     ZZ11
41706 2013 Level 3                     ZZ11
41707 2013 Level 3                     ZZ11
41708 2013 Level 3                     ZZ11
41709 2013 Level 3                     ZZ11
41710 2013 Level 3                     ZZ11
41711 2013 Level 3                     ZZ11
41712 2013 Level 3                     ZZ11
41713 2013 Level 3                     ZZ11
41714 2013 Level 3                     ZZ11
41715 2013 Level 3                     ZZ11
      Industry_name_NZSIOC       Units              Variable_code
1     All industries             Dollars (millions) H01
2     All industries             Dollars (millions) H04
3     All industries             Dollars (millions) H05
4     All industries             Dollars (millions) H07
5     All industries             Dollars (millions) H08
6     All industries             Dollars (millions) H09
7     All industries             Dollars (millions) H10
8     All industries             Dollars (millions) H11
9     All industries             Dollars (millions) H12
10    All industries             Dollars (millions) H13
11    All industries             Dollars (millions) H14
12    All industries             Dollars (millions) H19
13    All industries             Dollars (millions) H20
14    All industries             Dollars (millions) H21
15    All industries             Dollars (millions) H22
16    All industries             Dollars (millions) H23
17    All industries             Dollars (millions) H24
18    All industries             Dollars (millions) H25
19    All industries             Dollars (millions) H26
20    All industries             Dollars (millions) H29
21    All industries             Dollars (millions) H30
22    All industries             Dollars (millions) H31
23    All industries             Dollars (millions) H32
24    All industries             Dollars (millions) H33
25    All industries             Dollars            H34
26    All industries             Dollars            H35
27    All industries             Percentage         H36
28    All industries             Percentage         H37
29    All industries             Percentage         H39
30    All industries             Percentage         H40
⋮     ⋮                          ⋮                  ⋮
41686 Food product manufacturing Dollars (millions) H08
41687 Food product manufacturing Dollars (millions) H09
41688 Food product manufacturing Dollars (millions) H10
41689 Food product manufacturing Dollars (millions) H11
41690 Food product manufacturing Dollars (millions) H12
41691 Food product manufacturing Dollars (millions) H13
41692 Food product manufacturing Dollars (millions) H17
41693 Food product manufacturing Dollars (millions) H18
41694 Food product manufacturing Dollars (millions) H20
41695 Food product manufacturing Dollars (millions) H21
41696 Food product manufacturing Dollars (millions) H22
41697 Food product manufacturing Dollars (millions) H23
41698 Food product manufacturing Dollars (millions) H24
41699 Food product manufacturing Dollars (millions) H25
41700 Food product manufacturing Dollars (millions) H26
41701 Food product manufacturing Dollars (millions) H27
41702 Food product manufacturing Dollars (millions) H28
41703 Food product manufacturing Dollars (millions) H29
41704 Food product manufacturing Dollars (millions) H30
41705 Food product manufacturing Dollars (millions) H31
41706 Food product manufacturing Dollars (millions) H32
41707 Food product manufacturing Dollars (millions) H33
41708 Food product manufacturing Dollars            H34
41709 Food product manufacturing Dollars            H35
41710 Food product manufacturing Percentage         H36
41711 Food product manufacturing Percentage         H37
41712 Food product manufacturing Percentage         H38
41713 Food product manufacturing Percentage         H39
41714 Food product manufacturing Percentage         H40
41715 Food product manufacturing Percentage         H41
      Variable_name
1     Total income
2     Sales, government funding, grants and subsidies
3     Interest, dividends and donations
4     Non-operating income
5     Total expenditure
6     Interest and donations
7     Indirect taxes
8     Depreciation
9     Salaries and wages paid
10    Redundancy and severance
11    Salaries and wages to self employed commission agents
12    Purchases and other operating expenses
13    Non-operating expenses
14    Opening stocks
15    Closing stocks
16    Surplus before income tax
17    Total assets
18    Current assets
19    Fixed tangible assets
20    Other assets
21    Total equity and liabilities
22    Shareholders funds or owners equity
23    Current liabilities
24    Other liabilities
25    Total income per employee count
26    Surplus per employee count
27    Current ratio
28    Quick ratio
29    Return on equity
30    Return on total assets
⋮     ⋮
41686 Total expenditure
41687 Interest and donations
41688 Indirect taxes
41689 Depreciation
41690 Salaries and wages paid
41691 Redundancy and severance
41692 Purchases of goods bought for resale
41693 Other purchases and operating expenses
41694 Non-operating expenses
41695 Opening stocks
41696 Closing stocks
41697 Surplus before income tax
41698 Total assets
41699 Current assets
41700 Fixed tangible assets
41701 Additions to fixed assets
41702 Disposals of fixed assets
41703 Other assets
41704 Total equity and liabilities
41705 Shareholders funds or owners equity
41706 Current liabilities
41707 Other liabilities
41708 Total income per employee count
41709 Surplus per employee count
41710 Current ratio
41711 Quick ratio
41712 Margin on sales of goods for resale
41713 Return on equity
41714 Return on total assets
41715 Liabilities structure
      Variable_category     Value
1     Financial performance 757,504
2     Financial performance 674,890
3     Financial performance 49,593
4     Financial performance 33,020
5     Financial performance 654,404
6     Financial performance 26,138
7     Financial performance 6,991
8     Financial performance 27,801
9     Financial performance 123,620
10    Financial performance 275
11    Financial performance 2,085
12    Financial performance 452,963
13    Financial performance 14,806
14    Financial performance 68,896
15    Financial performance 69,127
16    Financial performance 103,330
17    Financial position    2,512,677
18    Financial position    730,587
19    Financial position    591,351
20    Financial position    1,190,739
21    Financial position    2,512,677
22    Financial position    813,949
23    Financial position    933,093
24    Financial position    765,635
25    Financial ratios      400,900
26    Financial ratios      54,700
27    Financial ratios      78
28    Financial ratios      71
29    Financial ratios      13
30    Financial ratios      4
⋮     ⋮                     ⋮
41686 Financial performance 35,502
41687 Financial performance 438
41688 Financial performance 82
41689 Financial performance 820
41690 Financial performance 3,894
41691 Financial performance 8
41692 Financial performance 1,679
41693 Financial performance 28,496
41694 Financial performance 93
41695 Financial performance 3,722
41696 Financial performance 4,041
41697 Financial performance 1,227
41698 Financial position    23,102
41699 Financial position    9,312
41700 Financial position    8,357
41701 Financial position    1,339
41702 Financial position    375
41703 Financial position    5,434
41704 Financial position    23,102
41705 Financial position    10,670
41706 Financial position    10,212
41707 Financial position    2,220
41708 Financial ratios      523,700
41709 Financial ratios      17,700
41710 Financial ratios      91
41711 Financial ratios      52
41712 Financial ratios      40
41713 Financial ratios      12
41714 Financial ratios      5
41715 Financial ratios      46
      Industry_code_ANZSIC06
1     ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
2     ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
3     ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
4     ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
5     ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
6     ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
7     ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
8     ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
9     ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
10    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
11    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
12    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
13    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
14    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
15    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
16    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
17    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
18    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
19    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
20    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
21    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
22    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
23    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
24    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
25    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
26    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
27    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
28    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
29    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
30    ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)
⋮     ⋮
41686 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41687 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41688 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41689 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41690 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41691 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41692 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41693 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41694 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41695 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41696 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41697 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41698 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41699 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41700 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41701 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41702 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41703 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41704 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41705 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41706 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41707 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41708 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41709 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41710 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41711 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41712 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41713 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41714 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119
41715 ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119

We willen alleen de eerste 10 regels zien met alle kolommen:

In [ ]:
print(data, n = 10, width = Inf)

# A tibble: 41,715 × 10
    Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC
   <int> <chr>                       <chr>                <chr>
 1  2021 Level 1                     99999                All industries
 2  2021 Level 1                     99999                All industries
 3  2021 Level 1                     99999                All industries
 4  2021 Level 1                     99999                All industries
 5  2021 Level 1                     99999                All industries
 6  2021 Level 1                     99999                All industries
 7  2021 Level 1                     99999                All industries
 8  2021 Level 1                     99999                All industries
 9  2021 Level 1                     99999                All industries
10  2021 Level 1                     99999                All industries
   Units              Variable_code
   <chr>              <chr>
 1 Dollars (millions) H01
 2 Dollars (millions) H04
 3 Dollars (millions) H05
 4 Dollars (millions) H07
 5 Dollars (millions) H08
 6 Dollars (millions) H09
 7 Dollars (millions) H10
 8 Dollars (millions) H11
 9 Dollars (millions) H12
10 Dollars (millions) H13
   Variable_name                                   Variable_category     Value
   <chr>                                           <chr>                 <chr>
 1 Total income                                    Financial performance 757,504
 2 Sales, government funding, grants and subsidies Financial performance 674,890
 3 Interest, dividends and donations               Financial performance 49,593
 4 Non-operating income                            Financial performance 33,020
 5 Total expenditure                               Financial performance 654,404
 6 Interest and donations                          Financial performance 26,138
 7 Indirect taxes                                  Financial performance 6,991
 8 Depreciation                                    Financial performance 27,801
 9 Salaries and wages paid                         Financial performance 123,620
10 Redundancy and severance                        Financial performance 275
   Industry_code_ANZSIC06
   <chr>
 1 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O…
 2 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O…
 3 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O…
 4 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O…
 5 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O…
 6 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O…
 7 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O…
 8 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O…
 9 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O…
10 ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O…
# … with 41,705 more rows

We willen alleen de inhoud van de kolom 'Industry_name_NZSIOC' zien:

In [ ]:
data$Industry_name_NZSIOC

Output hidden; open in https://colab.research.google.com to view.

Dat kan ook op deze manier (het is de 4e kolom uit de tabel):

In [ ]:
data[[4]]

Output hidden; open in https://colab.research.google.com to view.

We gaan rekenen met de waarden uit de kolom 'Value', die slaan we dus op in een aparte variabele:

In [ ]:
geld <- data$Value
mean(geld)

Warning message in mean.default(geld):
“argument is not numeric or logical: returning NA”

[1] NA

Dat werkt niet .. <br>
In kolom 'Value' staan characters, daar kunnen we niet mee rekenen. Moeten we eerst omzetten in getallen:

In [ ]:
echt_geld <- as.numeric(geld)
mean(echt_geld)

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

[1] NA

Ai, daar hebben we de NA's weer: eerst verwijderen ..

In [ ]:
echt_geld_zonder_NA <- na.omit(echt_geld)
mean(echt_geld_zonder_NA)

[1] 190.8765

Of alle NA's vullen:

In [ ]:
echt_geld_zonder_NA <- na.locf(echt_geld)
mean(echt_geld_zonder_NA)

[1] 221.7765

Kunnen we dit bestand nu ook weer opslaan als een csv-file?<br>
Natuurlijk:

In [ ]:
write.csv(echt_geld_zonder_NA, "echtgeld.csv")

# Excel-bestanden
We kunnen ook Excel-bestanden inlezen (en weer opslaan):

In [ ]:
install.packages(c("readxl","writexl")) 
library(readxl)
library(writexl)

Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
excel_data <- read_excel("/content/vustudentanalytics.xlsx")
head(excel_data)

     sex    age agegr placesize              region
1    FEMALE 57  45-59 URBAN 100,000-200,000  Lubuskie
2    MALE   20  16-24 RURAL AREAS            Podlaskie
3    FEMALE 18  16-24 URBAN 500,000 AND OVER Mazowieckie
4    FEMALE 78  65+   RURAL AREAS            Podlaskie
5    FEMALE 54  45-59 URBAN 100,000-200,000  Zachodnio-pomorskie
6    MALE   20  16-24 URBAN 100,000-200,000  Slaskie
7    FEMALE 39  35-44 RURAL AREAS            Wielkopolskie
8    MALE   39  35-44 URBAN 100,000-200,000  Lubuskie
9    FEMALE 43  35-44 RURAL AREAS            Swietokrzyskie
10   FEMALE 63  60-64 URBAN BELOW 20,000     Dolnoslaskie
11   FEMALE 38  35-44 URBAN 100,000-200,000  Kujawsko-pomorskie
12   FEMALE 73  65+   URBAN 200,000-500,000  Slaskie
13   FEMALE 54  45-59 URBAN 200,000-500,000  Slaskie
14   MALE   30  25-34 URBAN 200,000-500,000  Zachodnio-pomorskie
15   MALE   68  65+   RURAL AREAS            Pomorskie
16   MALE   61  60-64 RURAL AREAS            Mazowieckie
17   MALE   84  65+   RURAL AREAS            Slaskie
18   FEMALE 87  65+   URBAN 500,000 AND OVER Lodzkie
19   MALE   47  45-59 URBAN 100,000-200,000  Slaskie
20   MALE   45  45-59 RURAL AREAS            Podkarpackie
21   FEMALE 60  60-64 RURAL AREAS            Podkarpackie
22   MALE   27  25-34 RURAL AREAS            Mazowieckie
23   FEMALE 49  45-59 URBAN 20,000-100,000   Lubelskie
24   FEMALE 58  45-59 URBAN 200,000-500,000  Slaskie
25   MALE   30  25-34 RURAL AREAS            Podkarpackie
26   MALE   59  45-59 URBAN 100,000-200,000  Malopolskie
27   FEMALE 26  25-34 URBAN 500,000 AND OVER Dolnoslaskie
28   FEMALE 35  35-44 URBAN BELOW 20,000     Mazowieckie
29   MALE   17  16-24 URBAN BELOW 20,000     Zachodnio-pomorskie
30   FEMALE 40  35-44 URBAN 20,000-100,000   Lubelskie
⋮    ⋮      ⋮   ⋮     ⋮                      ⋮
4971 FEMALE 41  35-44 RURAL AREAS            Pomorskie
4972 FEMALE 64  60-64 URBAN 100,000-200,000  Lodzkie
4973 FEMALE 30  25-34 URBAN BELOW 20,000     Podkarpackie
4974 MALE   85  65+   URBAN 100,000-200,000  Slaskie
4975 MALE   36  35-44 URBAN BELOW 20,000     Kujawsko-pomorskie
4976 FEMALE 19  16-24 RURAL AREAS            Opolskie
4977 FEMALE 44  NA    RURAL AREAS            Slaskie
4978 FEMALE 41  35-44 RURAL AREAS            Lodzkie
4979 MALE   58  45-59 URBAN 500,000 AND OVER Mazowieckie
4980 FEMALE 18  16-24 URBAN BELOW 20,000     Pomorskie
4981 MALE   47  45-59 URBAN 100,000-200,000  Dolnoslaskie
4982 MALE   62  60-64 URBAN 100,000-200,000  Swietokrzyskie
4983 MALE   80  65+   RURAL AREAS            Zachodnio-pomorskie
4984 MALE   75  65+   URBAN 500,000 AND OVER Lodzkie
4985 FEMALE 37  35-44 URBAN 200,000-500,000  Slaskie
4986 MALE   53  45-59 URBAN 500,000 AND OVER Lodzkie
4987 MALE   76  65+   URBAN 20,000-100,000   Swietokrzyskie
4988 MALE   40  35-44 URBAN 500,000 AND OVER Dolnoslaskie
4989 FEMALE 19  16-24 RURAL AREAS            Kujawsko-pomorskie
4990 MALE   66  65+   URBAN 100,000-200,000  Zachodnio-pomorskie
4991 MALE   31  25-34 RURAL AREAS            Mazowieckie
4992 FEMALE 48  45-59 URBAN BELOW 20,000     Warminsko-mazurskie
4993 FEMALE 28  25-34 URBAN 500,000 AND OVER Lodzkie
4994 FEMALE 30  25-34 RURAL AREAS            Swietokrzyskie
4995 MALE   68  65+   URBAN 20,000-100,000   Pomorskie
4996 MALE   56  45-59 URBAN 20,000-100,000   Swietokrzyskie
4997 FEMALE 59  45-59 RURAL AREAS            Swietokrzyskie
4998 FEMALE 20  16-24 RURAL AREAS            Kujawsko-pomorskie
4999 MALE   34  25-34 RURAL AREAS            Dolnoslaskie
5000 MALE   36  35-44 RURAL AREAS            Zachodnio-pomorskie
     edu
1    VOCATIONAL/GRAMMAR
2    VOCATIONAL/GRAMMAR
3    VOCATIONAL/GRAMMAR
4    PRIMARY/NO EDUCATION
5    VOCATIONAL/GRAMMAR
6    SECONDARY
7    SECONDARY
8    SECONDARY
9    SECONDARY
10   SECONDARY
11   VOCATIONAL/GRAMMAR
12   VOCATIONAL/GRAMMAR
13   SECONDARY
14   VOCATIONAL/GRAMMAR
15   SECONDARY
16   PRIMARY/NO EDUCATION
17   PRIMARY/NO EDUCATION
18   SECONDARY
19   PRIMARY/NO EDUCATION
20   VOCATIONAL/GRAMMAR
21   VOCATIONAL/GRAMMAR
22   VOCATIONAL/GRAMMAR
23   POST-SECONDARY OR HIGHER
24   POST-SECONDARY OR HIGHER
25   VOCATIONAL/GRAMMAR
26   SECONDARY
27   POST-SECONDARY OR HIGHER
28   SECONDARY
29   PRIMARY/NO EDUCATION
30   POST-SECONDARY OR HIGHER
⋮    ⋮
4971 VOCATIONAL/GRAMMAR
4972 SECONDARY
4973 SECONDARY
4974 VOCATIONAL/GRAMMAR
4975 SECONDARY
4976 SECONDARY
4977 PRIMARY/NO EDUCATION
4978 SECONDARY
4979 SECONDARY
4980 VOCATIONAL/GRAMMAR
4981 VOCATIONAL/GRAMMAR
4982 SECONDARY
4983 PRIMARY/NO EDUCATION
4984 POST-SECONDARY OR HIGHER
4985 SECONDARY
4986 POST-SECONDARY OR HIGHER
4987 PRIMARY/NO EDUCATION
4988 POST-SECONDARY OR HIGHER
4989 VOCATIONAL/GRAMMAR
4990 VOCATIONAL/GRAMMAR
4991 SECONDARY
4992 POST-SECONDARY OR HIGHER
4993 POST-SECONDARY OR HIGHER
4994 POST-SECONDARY OR HIGHER
4995 PRIMARY/NO EDUCATION
4996 SECONDARY
4997 SECONDARY
4998 SECONDARY
4999 SECONDARY
5000 PRIMARY/NO EDUCATION
     eduspec
1    services for the population and transport services
2    no specialisation
3    no specialisation
4    no specialisation
5    agriculture, forestry, fishing
6    no specialisation
7    art
8    technical science
9    social sciences
10   no specialisation
11   services for the population and transport services
12   services for the population and transport services
13   social sciences
14   social sciences
15   no specialisation
16   no specialisation
17   no specialisation
18   social sciences
19   no specialisation
20   technical science
21   agriculture, forestry, fishing
22   no specialisation
23   social sciences
24   pedagogics
25   services for the population and transport services
26   services for the population and transport services
27   pedagogics
28   social sciences
29   no specialisation
30   law
⋮    ⋮
4971 production and processing
4972 no specialisation
4973 no specialisation
4974 technical science
4975 no specialisation
4976 no specialisation
4977 no specialisation
4978 technical science
4979 technical science
4980 no specialisation
4981 architecture and construction
4982 not applicable
4983 no specialisation
4984 physical sciences
4985 healthcare
4986 technical science
4987 not applicable
4988 technical science
4989 no specialisation
4990 services for the population and transport services
4991 technical science
4992 pedagogics
4993 pedagogics
4994 social sciences
4995 no specialisation
4996 technical science
4997 agriculture, forestry, fishing
4998 computer science
4999 agriculture, forestry, fishing
5000 no specialisation
     socprof                     unempdur income ⋯ alcsol workab wkabdur
1    RETIRED                      0       800    ⋯ NO     NO     -8
2    PUPIL OR STUDENT            -8       350    ⋯ NO     NO     -8
3    PUPIL OR STUDENT            -8       NA     ⋯ NO     NA     -8
4    RETIRED                     -8       900    ⋯ NO     NO     -8
5    SELF-EMPLOYED               -8       1500   ⋯ NO     NO     -8
6    PUPIL OR STUDENT             0       -8     ⋯ NO     NO     -8
7    EMPLOYED IN PUBLIC SECTOR    0       2000   ⋯ NO     NO     -8
8    EMPLOYED IN PRIVATE SECTOR   7       1197   ⋯ NO     NO     -8
9    EMPLOYED IN PUBLIC SECTOR   16       580    ⋯ NO     NO     -8
10   RETIRED                     24       1400   ⋯ NO     NO     -8
11   EMPLOYED IN PRIVATE SECTOR  -8       1500   ⋯ NO     YES     4
12   LONG-TERM SICK/DISABLED     24       1700   ⋯ NO     NO     -8
13   EMPLOYED IN PRIVATE SECTOR   0       2000   ⋯ NO     NO     -8
14   EMPLOYED IN PRIVATE SECTOR   0       900    ⋯ NO     NO     -8
15   RETIRED                      0       -8     ⋯ NO     NO     -8
16   FARMER                       0       -8     ⋯ NO     NO     -8
17   RETIRED                     24       2000   ⋯ NO     NO     -8
18   RETIRED                     24       1400   ⋯ NO     NO     -8
19   UNEMPLOYED                   8       560    ⋯ NO     NO     -8
20   UNEMPLOYED                   8       530    ⋯ NO     NO     -8
21   LONG-TERM SICK/DISABLED     -8       700    ⋯ NO     NO     -8
22   EMPLOYED IN PRIVATE SECTOR   3       1000   ⋯ NO     NO     -8
23   SELF-EMPLOYED               -8       -8     ⋯ NO     NO     -8
24   EMPLOYED IN PUBLIC SECTOR    0       3500   ⋯ NO     NO     -8
25   SELF-EMPLOYED               -8       1600   ⋯ NO     NO     -8
26   RETIRED                      0       1300   ⋯ YES    NO     -8
27   EMPLOYED IN PRIVATE SECTOR  -8       1500   ⋯ NO     YES    24
28   LONG-TERM SICK/DISABLED      0       1300   ⋯ NO     NO     -8
29   PUPIL OR STUDENT            -8       NA     ⋯ NO     NA     -8
30   EMPLOYED IN PRIVATE SECTOR  -8       2000   ⋯ NO     NO     -8
⋮    ⋮                           ⋮        ⋮      ⋱ ⋮      ⋮      ⋮
4971 UNEMPLOYED                  17       NA     ⋯ NO     YES    12
4972 RETIRED                      0       690    ⋯ NA     NO     -8
4973 OTHER ECONOMICALLY INACTIVE  0       550    ⋯ NO     NO     -8
4974 RETIRED                     24       3450   ⋯ NO     NO     -8
4975 EMPLOYED IN PRIVATE SECTOR   0       2300   ⋯ NO     NO     -8
4976 PUPIL OR STUDENT            -8       NA     ⋯ NO     NO     -8
4977 UNEMPLOYED                   8       468    ⋯ NO     NO     -8
4978 SELF-EMPLOYED                0       -8     ⋯ NO     NO     -8
4979 SELF-EMPLOYED                0       -8     ⋯ NO     NO     -8
4980 PUPIL OR STUDENT             0       NA     ⋯ NO     NA     -8
4981 SELF-EMPLOYED                0       6000   ⋯ NO     YES    34
4982 RETIRED                     -8       1800   ⋯ NO     NO     -8
4983 RETIRED                     -8       1100   ⋯ NO     NO     -8
4984 RETIRED                     24       2400   ⋯ NO     NO     -8
4985 EMPLOYED IN PUBLIC SECTOR    0       2000   ⋯ NO     NO     -8
4986 UNEMPLOYED                   2       1000   ⋯ NO     NO     -8
4987 RETIRED                     24       800    ⋯ NO     NO     -8
4988 EMPLOYED IN PRIVATE SECTOR   0       -8     ⋯ NO     NO     -8
4989 UNEMPLOYED                   4       -8     ⋯ NO     NA     -8
4990 RETIRED                      0       1600   ⋯ NO     NO     -8
4991 EMPLOYED IN PUBLIC SECTOR    0       2500   ⋯ YES    NO     -8
4992 EMPLOYED IN PUBLIC SECTOR    0       3000   ⋯ NO     NO     -8
4993 EMPLOYED IN PUBLIC SECTOR    0       1800   ⋯ NO     NO     -8
4994 FARMER                      -8       NA     ⋯ NO     NO     -8
4995 RETIRED                      0       -8     ⋯ NO     NO     -8
4996 EMPLOYED IN PRIVATE SECTOR  -8       2500   ⋯ NO     NO     -8
4997 OTHER ECONOMICALLY INACTIVE -8       -8     ⋯ NO     NO     -8
4998 EMPLOYED IN PRIVATE SECTOR   0       1000   ⋯ NO     NO     -8
4999 EMPLOYED IN PUBLIC SECTOR    0       2600   ⋯ NO     NO     -8
5000 OTHER ECONOMICALLY INACTIVE 24       NA     ⋯ NO     NO     -8
     wkabint            wkabintdur       emcc        englang height weight
1    NO                 NA               NA          NONE    170    89
2    NO                 NA               NA          ACTIVE  187    82
3    NO                 NA               NA          ACTIVE  165    50
4    NO                 NA               NA          NONE    160    78
5    NO                 NA               NA          NONE    158    50
6    NO                 NA               NA          ACTIVE  165    65
7    NO                 NA               NA          PASSIVE 168    68
8    NO                 NA               NA          NONE    171    86
9    NO                 NA               NA          NONE    167    54
10   NO                 NA               NA          NONE    155    65
11   NO                 NA               NA          NONE    180    77
12   NO                 NA               NA          NONE    168    78
13   NO                 NA               NA          NONE    170    75
14   NO                 NA               NA          NONE    170    74
15   NO                 NA               NA          NA      165    65
16   NO                 NA               NA          NONE    NA     NA
17   NO                 NA               NA          NONE    170    56
18   NO                 NA               NA          NONE    155    75
19   NO                 NA               NA          NONE    164    70
20   YES, TO EU COUNTRY IT DEPENDS       GERMANY     NONE    181    78
21   NO                 NA               NA          NONE    164    100
22   NO                 NA               NA          NONE    175    97
23   NO                 NA               NA          NONE    160    60
24   NO                 NA               NA          NONE    162    59
25   NO                 NA               NA          NONE    174    75
26   NO                 NA               NA          NONE    176    68
27   NO                 NA               NA          ACTIVE  160    58
28   NO                 NA               NA          NONE    158    52
29   NO                 NA               NA          PASSIVE 178    50
30   NO                 NA               NA          ACTIVE  159    57
⋮    ⋮                  ⋮                ⋮           ⋮       ⋮      ⋮
4971 YES, TO EU COUNTRY LESS THAN 1 YEAR NETHERLANDS NONE    164    70
4972 NO                 NA               NA          NONE    164    62
4973 NO                 NA               NA          PASSIVE 168    65
4974 NO                 NA               NA          NONE    166    60
4975 NO                 NA               NA          NONE    183    90
4976 NO                 NA               NA          ACTIVE  174    60
4977 NO                 NA               NA          NONE    164    58
4978 NO                 NA               NA          PASSIVE 170    72
4979 NO                 NA               NA          NONE    170    70
4980 NO                 NA               NA          ACTIVE  170    60
4981 YES, TO EU COUNTRY LESS THAN 1 YEAR GERMANY     NONE    170    62
4982 NO                 NA               NA          NONE    155    80
4983 NO                 NA               NA          NONE    165    69
4984 NO                 NA               NA          NONE    176    82
4985 NO                 NA               NA          NONE    156    57
4986 NO                 NA               NA          PASSIVE 181    85
4987 NO                 NA               NA          NONE    178    76
4988 NO                 NA               NA          ACTIVE  184    86
4989 NO                 NA               NA          NONE    171    80
4990 NO                 NA               NA          NONE    168    95
4991 NO                 NA               NA          ACTIVE  193    95
4992 NO                 NA               NA          PASSIVE 169    75
4993 NO                 NA               NA          ACTIVE  175    57
4994 NO                 NA               NA          PASSIVE 168    60
4995 NO                 NA               NA          NONE    175    97
4996 NO                 NA               NA          NONE    176    NA
4997 NO                 NA               NA          NONE    164    80
4998 NO                 NA               NA          ACTIVE  160    50
4999 NO                 NA               NA          NONE    178    82
5000 NO                 NA               NA          NONE    165    70
     bmi
1    30,79585
2    23,44934
3    18,36547
4    30,46875
5    20,02884
6    23,87511
7    24,09297
8    29,41076
9    19,36247
10   27,05515
11   23,76543
12   27,63605
13   25,95156
14   25,60554
15   23,87511
16   NA
17   19,37716
18   31,21748
19   26,02617
20   23,80880
21   37,18025
22   31,67347
23   23,43750
24   22,48133
25   24,77210
26   21,95248
27   22,65625
28   20,83000
29   15,78084
30   22,54658
⋮    ⋮
4971 26,02617
4972 23,05175
4973 23,03005
4974 21,77384
4975 26,87450
4976 19,81768
4977 NA
4978 24,91349
4979 24,22145
4980 20,76125
4981 21,45329
4982 33,29865
4983 25,34435
4984 26,47211
4985 23,42209
4986 25,94548
4987 23,98687
4988 25,40170
4989 27,35885
4990 33,65930
4991 25,50404
4992 26,25958
4993 18,61224
4994 21,25850
4995 31,67347
4996 NA
4997 29,74420
4998 19,53125
4999 25,88057
5000 25,71166

En vervolgens alle blok 1 opdrachten ook in R maken .. maar dat lijkt me iets voor de Kerstvakantie :)

Vooruit, 1 grafiekje:

In [ ]:
ggplot(data = excel_data) + 
  geom_bar(mapping = aes(x = age))

Je kunt in ieder geval ook dit Excel-bestand weer opslaan:

In [ ]:
write_xlsx(excel_data, "opgeslagenstudentenbestand.xlsx")

# Intermezzo: lezen en opslaan met R of R Studio
Let Op: als je in plaats van de Colab R of R Studio gebruikt, moet je je csv- en/of Excel-bestand in de juiste map zetten om deze te laten inlezen:<br>
- de Documents-folder op je pc

Als je een bestand opslaat, komt het bestand ook in die map terecht.<br>

Als je bestanden in een andere map staan:<br>
- excel_data <- read_excel("Mapnaam\\naam_van_excelbestand.xlsx") of
- excel_data <- read_excel("Mapnaam1\\Mapnaam2\\naam_van_excelbestand.xlsx")

# Database-bestanden met [DBI](https://dbi.r-dbi.org/://)
Eens kijken of we ook [RSQLite-databases](https://rsqlite.r-dbi.org/://) kunnen inlezen in R:

In [ ]:
install.packages("DBI")
install.packages("RSQLite")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘Rcpp’, ‘plogr’

In [ ]:
library(DBI)
library(RSQLite)

In [ ]:
# Create an ephemeral in-memory RSQLite database
con <- dbConnect(RSQLite::SQLite(), dbname = ":memory:")
dbListTables(con)

character(0)

In [ ]:
dbWriteTable(con, "mtcars", mtcars)
dbListTables(con)

[1] "mtcars"

In [ ]:
dbListFields(con, "mtcars")
dbReadTable(con, "mtcars")

 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"

   mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
1  21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
2  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
3  22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
4  21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
5  18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
6  18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
7  14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
8  24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
9  22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
10 19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
11 17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
12 16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
13 17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
14 15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
15 10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
16 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
17 14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
18 32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
19 30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
20 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
21 21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
22 15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
23 15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
24 13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
25 19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
26 27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
27 26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
28 30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
29 15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
30 19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
31 15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
32 21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
# You can fetch all results:
res <- dbSendQuery(con, "SELECT * FROM mtcars WHERE cyl = 4")
dbFetch(res)
dbClearResult(res)

   mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
1  22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
2  24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
3  22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
4  32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
5  30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
6  33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
7  21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
8  27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
9  26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
10 30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
11 21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
# Or a chunk at a time
res <- dbSendQuery(con, "SELECT * FROM mtcars WHERE cyl = 4")
while(!dbHasCompleted(res)){
  chunk <- dbFetch(res, n = 5)
  print(nrow(chunk))
}

[1] 5
[1] 5
[1] 1

In [ ]:
dbClearResult(res)

In [ ]:
dbDisconnect(con)

Je kunt dus ook een verbinding maken met een SQL-database en data uit die database inlezen in R en be-/verwerken.

# SPSS-bestanden
Als je liever met R dan met SPSS (of SAS of Stata) werkt, kun je een SPSS-bestand ook inlezen in R. Daarbij gebruik je de library [Haven](https://haven.tidyverse.org/://), die al standaard met de Tidyverse wordt geinstalleerd:

In [ ]:
library(haven)

# SPSS
spss <- read_sav("VUstudentanalytics.sav")
spss

     sex    age agegr placesize              region
1    FEMALE 57  45-59 URBAN 100,000-200,000  Lubuskie
2    MALE   20  16-24 RURAL AREAS            Podlaskie
3    FEMALE 18  16-24 URBAN 500,000 AND OVER Mazowieckie
4    FEMALE 78  65+   RURAL AREAS            Podlaskie
5    FEMALE 54  45-59 URBAN 100,000-200,000  Zachodnio-pomorskie
6    MALE   20  16-24 URBAN 100,000-200,000  Slaskie
7    FEMALE 39  35-44 RURAL AREAS            Wielkopolskie
8    MALE   39  35-44 URBAN 100,000-200,000  Lubuskie
9    FEMALE 43  35-44 RURAL AREAS            Swietokrzyskie
10   FEMALE 63  60-64 URBAN BELOW 20,000     Dolnoslaskie
11   FEMALE 38  35-44 URBAN 100,000-200,000  Kujawsko-pomorskie
12   FEMALE 73  65+   URBAN 200,000-500,000  Slaskie
13   FEMALE 54  45-59 URBAN 200,000-500,000  Slaskie
14   MALE   30  25-34 URBAN 200,000-500,000  Zachodnio-pomorskie
15   MALE   68  65+   RURAL AREAS            Pomorskie
16   MALE   61  60-64 RURAL AREAS            Mazowieckie
17   MALE   84  65+   RURAL AREAS            Slaskie
18   FEMALE 87  65+   URBAN 500,000 AND OVER Lodzkie
19   MALE   47  45-59 URBAN 100,000-200,000  Slaskie
20   MALE   45  45-59 RURAL AREAS            Podkarpackie
21   FEMALE 60  60-64 RURAL AREAS            Podkarpackie
22   MALE   27  25-34 RURAL AREAS            Mazowieckie
23   FEMALE 49  45-59 URBAN 20,000-100,000   Lubelskie
24   FEMALE 58  45-59 URBAN 200,000-500,000  Slaskie
25   MALE   30  25-34 RURAL AREAS            Podkarpackie
26   MALE   59  45-59 URBAN 100,000-200,000  Malopolskie
27   FEMALE 26  25-34 URBAN 500,000 AND OVER Dolnoslaskie
28   FEMALE 35  35-44 URBAN BELOW 20,000     Mazowieckie
29   MALE   17  16-24 URBAN BELOW 20,000     Zachodnio-pomorskie
30   FEMALE 40  35-44 URBAN 20,000-100,000   Lubelskie
⋮    ⋮      ⋮   ⋮     ⋮                      ⋮
4971 FEMALE 41  35-44 RURAL AREAS            Pomorskie
4972 FEMALE 64  60-64 URBAN 100,000-200,000  Lodzkie
4973 FEMALE 30  25-34 URBAN BELOW 20,000     Podkarpackie
4974 MALE   85  65+   URBAN 100,000-200,000  Slaskie
4975 MALE   36  35-44 URBAN BELOW 20,000     Kujawsko-pomorskie
4976 FEMALE 19  16-24 RURAL AREAS            Opolskie
4977 FEMALE 44  NA    RURAL AREAS            Slaskie
4978 FEMALE 41  35-44 RURAL AREAS            Lodzkie
4979 MALE   58  45-59 URBAN 500,000 AND OVER Mazowieckie
4980 FEMALE 18  16-24 URBAN BELOW 20,000     Pomorskie
4981 MALE   47  45-59 URBAN 100,000-200,000  Dolnoslaskie
4982 MALE   62  60-64 URBAN 100,000-200,000  Swietokrzyskie
4983 MALE   80  65+   RURAL AREAS            Zachodnio-pomorskie
4984 MALE   75  65+   URBAN 500,000 AND OVER Lodzkie
4985 FEMALE 37  35-44 URBAN 200,000-500,000  Slaskie
4986 MALE   53  45-59 URBAN 500,000 AND OVER Lodzkie
4987 MALE   76  65+   URBAN 20,000-100,000   Swietokrzyskie
4988 MALE   40  35-44 URBAN 500,000 AND OVER Dolnoslaskie
4989 FEMALE 19  16-24 RURAL AREAS            Kujawsko-pomorskie
4990 MALE   66  65+   URBAN 100,000-200,000  Zachodnio-pomorskie
4991 MALE   31  25-34 RURAL AREAS            Mazowieckie
4992 FEMALE 48  45-59 URBAN BELOW 20,000     Warminsko-mazurskie
4993 FEMALE 28  25-34 URBAN 500,000 AND OVER Lodzkie
4994 FEMALE 30  25-34 RURAL AREAS            Swietokrzyskie
4995 MALE   68  65+   URBAN 20,000-100,000   Pomorskie
4996 MALE   56  45-59 URBAN 20,000-100,000   Swietokrzyskie
4997 FEMALE 59  45-59 RURAL AREAS            Swietokrzyskie
4998 FEMALE 20  16-24 RURAL AREAS            Kujawsko-pomorskie
4999 MALE   34  25-34 RURAL AREAS            Dolnoslaskie
5000 MALE   36  35-44 RURAL AREAS            Zachodnio-pomorskie
     edu
1    VOCATIONAL/GRAMMAR
2    VOCATIONAL/GRAMMAR
3    VOCATIONAL/GRAMMAR
4    PRIMARY/NO EDUCATION
5    VOCATIONAL/GRAMMAR
6    SECONDARY
7    SECONDARY
8    SECONDARY
9    SECONDARY
10   SECONDARY
11   VOCATIONAL/GRAMMAR
12   VOCATIONAL/GRAMMAR
13   SECONDARY
14   VOCATIONAL/GRAMMAR
15   SECONDARY
16   PRIMARY/NO EDUCATION
17   PRIMARY/NO EDUCATION
18   SECONDARY
19   PRIMARY/NO EDUCATION
20   VOCATIONAL/GRAMMAR
21   VOCATIONAL/GRAMMAR
22   VOCATIONAL/GRAMMAR
23   POST-SECONDARY OR HIGHER
24   POST-SECONDARY OR HIGHER
25   VOCATIONAL/GRAMMAR
26   SECONDARY
27   POST-SECONDARY OR HIGHER
28   SECONDARY
29   PRIMARY/NO EDUCATION
30   POST-SECONDARY OR HIGHER
⋮    ⋮
4971 VOCATIONAL/GRAMMAR
4972 SECONDARY
4973 SECONDARY
4974 VOCATIONAL/GRAMMAR
4975 SECONDARY
4976 SECONDARY
4977 PRIMARY/NO EDUCATION
4978 SECONDARY
4979 SECONDARY
4980 VOCATIONAL/GRAMMAR
4981 VOCATIONAL/GRAMMAR
4982 SECONDARY
4983 PRIMARY/NO EDUCATION
4984 POST-SECONDARY OR HIGHER
4985 SECONDARY
4986 POST-SECONDARY OR HIGHER
4987 PRIMARY/NO EDUCATION
4988 POST-SECONDARY OR HIGHER
4989 VOCATIONAL/GRAMMAR
4990 VOCATIONAL/GRAMMAR
4991 SECONDARY
4992 POST-SECONDARY OR HIGHER
4993 POST-SECONDARY OR HIGHER
4994 POST-SECONDARY OR HIGHER
4995 PRIMARY/NO EDUCATION
4996 SECONDARY
4997 SECONDARY
4998 SECONDARY
4999 SECONDARY
5000 PRIMARY/NO EDUCATION
     eduspec
1    services for the population and transport services
2    no specialisation
3    no specialisation
4    no specialisation
5    agriculture, forestry, fishing
6    no specialisation
7    art
8    technical science
9    social sciences
10   no specialisation
11   services for the population and transport services
12   services for the population and transport services
13   social sciences
14   social sciences
15   no specialisation
16   no specialisation
17   no specialisation
18   social sciences
19   no specialisation
20   technical science
21   agriculture, forestry, fishing
22   no specialisation
23   social sciences
24   pedagogics
25   services for the population and transport services
26   services for the population and transport services
27   pedagogics
28   social sciences
29   no specialisation
30   law
⋮    ⋮
4971 production and processing
4972 no specialisation
4973 no specialisation
4974 technical science
4975 no specialisation
4976 no specialisation
4977 no specialisation
4978 technical science
4979 technical science
4980 no specialisation
4981 architecture and construction
4982 not applicable
4983 no specialisation
4984 physical sciences
4985 healthcare
4986 technical science
4987 not applicable
4988 technical science
4989 no specialisation
4990 services for the population and transport services
4991 technical science
4992 pedagogics
4993 pedagogics
4994 social sciences
4995 no specialisation
4996 technical science
4997 agriculture, forestry, fishing
4998 computer science
4999 agriculture, forestry, fishing
5000 no specialisation
     socprof                     unempdur income ⋯ sport_transformed
1    RETIRED                      0         800  ⋯ 1
2    PUPIL OR STUDENT            -8         350  ⋯ 1
3    PUPIL OR STUDENT            -8       NA     ⋯ 1
4    RETIRED                     -8         900  ⋯ 2
5    SELF-EMPLOYED               -8        1500  ⋯ 2
6    PUPIL OR STUDENT             0          -8  ⋯ 1
7    EMPLOYED IN PUBLIC SECTOR    0        2000  ⋯ 2
8    EMPLOYED IN PRIVATE SECTOR   7        1197  ⋯ 1
9    EMPLOYED IN PUBLIC SECTOR   16         580  ⋯ 2
10   RETIRED                     24        1400  ⋯ 2
11   EMPLOYED IN PRIVATE SECTOR  -8        1500  ⋯ 2
12   LONG-TERM SICK/DISABLED     24        1700  ⋯ 2
13   EMPLOYED IN PRIVATE SECTOR   0        2000  ⋯ 2
14   EMPLOYED IN PRIVATE SECTOR   0         900  ⋯ 2
15   RETIRED                      0          -8  ⋯ 1
16   FARMER                       0          -8  ⋯ 2
17   RETIRED                     24        2000  ⋯ 2
18   RETIRED                     24        1400  ⋯ 2
19   UNEMPLOYED                   8         560  ⋯ 2
20   UNEMPLOYED                   8         530  ⋯ 2
21   LONG-TERM SICK/DISABLED     -8         700  ⋯ 2
22   EMPLOYED IN PRIVATE SECTOR   3        1000  ⋯ 2
23   SELF-EMPLOYED               -8          -8  ⋯ 1
24   EMPLOYED IN PUBLIC SECTOR    0        3500  ⋯ 2
25   SELF-EMPLOYED               -8        1600  ⋯ 2
26   RETIRED                      0        1300  ⋯ 2
27   EMPLOYED IN PRIVATE SECTOR  -8        1500  ⋯ 1
28   LONG-TERM SICK/DISABLED      0        1300  ⋯ 2
29   PUPIL OR STUDENT            -8       NA     ⋯ 1
30   EMPLOYED IN PRIVATE SECTOR  -8        2000  ⋯ 1
⋮    ⋮                           ⋮        ⋮      ⋱ ⋮
4971 UNEMPLOYED                  17       NA     ⋯ 1
4972 RETIRED                      0         690  ⋯ 2
4973 OTHER ECONOMICALLY INACTIVE  0         550  ⋯ 1
4974 RETIRED                     24        3450  ⋯ 1
4975 EMPLOYED IN PRIVATE SECTOR   0        2300  ⋯ 1
4976 PUPIL OR STUDENT            -8       NA     ⋯ 1
4977 UNEMPLOYED                   8         468  ⋯ 0
4978 SELF-EMPLOYED                0          -8  ⋯ 2
4979 SELF-EMPLOYED                0          -8  ⋯ 1
4980 PUPIL OR STUDENT             0       NA     ⋯ 2
4981 SELF-EMPLOYED                0        6000  ⋯ 2
4982 RETIRED                     -8        1800  ⋯ 2
4983 RETIRED                     -8        1100  ⋯ 2
4984 RETIRED                     24        2400  ⋯ 2
4985 EMPLOYED IN PUBLIC SECTOR    0        2000  ⋯ 1
4986 UNEMPLOYED                   2        1000  ⋯ 2
4987 RETIRED                     24         800  ⋯ 2
4988 EMPLOYED IN PRIVATE SECTOR   0          -8  ⋯ 1
4989 UNEMPLOYED                   4          -8  ⋯ 1
4990 RETIRED                      0        1600  ⋯ 1
4991 EMPLOYED IN PUBLIC SECTOR    0        2500  ⋯ 1
4992 EMPLOYED IN PUBLIC SECTOR    0        3000  ⋯ 1
4993 EMPLOYED IN PUBLIC SECTOR    0        1800  ⋯ 2
4994 FARMER                      -8       NA     ⋯ 2
4995 RETIRED                      0          -8  ⋯ 1
4996 EMPLOYED IN PRIVATE SECTOR  -8        2500  ⋯ 2
4997 OTHER ECONOMICALLY INACTIVE -8          -8  ⋯ 2
4998 EMPLOYED IN PRIVATE SECTOR   0        1000  ⋯ 2
4999 EMPLOYED IN PUBLIC SECTOR    0        2600  ⋯ 1
5000 OTHER ECONOMICALLY INACTIVE 24       NA     ⋯ 2
     smoke_transformed alcabuse_transformed alcsol_transformed
1    2                 2                    2
2    2                 2                    2
3    2                 2                    2
4    2                 2                    2
5    1                 2                    2
6    2                 2                    2
7    2                 2                    2
8    2                 2                    2
9    1                 2                    2
10   1                 2                    2
11   1                 2                    2
12   2                 2                    2
13   1                 2                    2
14   1                 2                    2
15   2                 2                    2
16   1                 2                    2
17   2                 2                    2
18   2                 2                    2
19   1                 2                    2
20   1                 2                    2
21   2                 2                    2
22   1                 2                    2
23   1                 2                    2
24   1                 2                    2
25   2                 2                    2
26   1                 1                    1
27   2                 2                    2
28   2                 2                    2
29   2                 2                    2
30   1                 2                    2
⋮    ⋮                 ⋮                    ⋮
4971 2                 2                    2
4972 2                 2                    0
4973 2                 2                    2
4974 2                 2                    2
4975 2                 2                    2
4976 2                 2                    2
4977 1                 2                    2
4978 2                 2                    2
4979 1                 2                    2
4980 2                 2                    2
4981 1                 2                    2
4982 2                 2                    2
4983 2                 2                    2
4984 2                 2                    2
4985 1                 2                    2
4986 1                 2                    2
4987 2                 2                    2
4988 2                 2                    2
4989 2                 2                    2
4990 2                 2                    2
4991 1                 2                    1
4992 2                 2                    2
4993 2                 2                    2
4994 2                 2                    2
4995 2                 2                    2
4996 2                 2                    2
4997 1                 2                    2
4998 2                 2                    2
4999 2                 2                    2
5000 1                 1                    2
     workab_transformed wkabint_transformed wkabintdur_transformed
1    2                  3                   5
2    2                  3                   5
3    1                  3                   5
4    2                  3                   5
5    2                  3                   5
6    2                  3                   5
7    2                  3                   5
8    2                  3                   5
9    2                  3                   5
10   2                  3                   5
11   0                  3                   5
12   2                  3                   5
13   2                  3                   5
14   2                  3                   5
15   2                  3                   5
16   2                  3                   5
17   2                  3                   5
18   2                  3                   5
19   2                  3                   5
20   2                  2                   4
21   2                  3                   5
22   2                  3                   5
23   2                  3                   5
24   2                  3                   5
25   2                  3                   5
26   2                  3                   5
27   0                  3                   5
28   2                  3                   5
29   1                  3                   5
30   2                  3                   5
⋮    ⋮                  ⋮                   ⋮
4971 0                  2                   3
4972 2                  3                   5
4973 2                  3                   5
4974 2                  3                   5
4975 2                  3                   5
4976 2                  3                   5
4977 2                  3                   5
4978 2                  3                   5
4979 2                  3                   5
4980 1                  3                   5
4981 0                  2                   3
4982 2                  3                   5
4983 2                  3                   5
4984 2                  3                   5
4985 2                  3                   5
4986 2                  3                   5
4987 2                  3                   5
4988 2                  3                   5
4989 1                  3                   5
4990 2                  3                   5
4991 2                  3                   5
4992 2                  3                   5
4993 2                  3                   5
4994 2                  3                   5
4995 2                  3                   5
4996 2                  3                   5
4997 2                  3                   5
4998 2                  3                   5
4999 2                  3                   5
5000 2                  3                   5
     emcc_transformed englang_transformed depress_transformed
1    17               3                   15
2    17               2                   21
3    17               2                   21
4    17               3                    5
5    17               3                   17
6    17               2                   16
7    17               1                   20
8    17               3                   17
9    17               3                   21
10   17               3                   15
11   17               3                   21
12   17               3                   15
13   17               3                   17
14   17               3                   19
15   17               0                   19
16   17               3                   21
17   17               3                   10
18   17               3                   10
19   17               3                   18
20   16               3                   17
21   17               3                   13
22   17               3                   21
23   17               3                   18
24   17               3                   20
25   17               3                   21
26   17               3                   12
27   17               2                   18
28   17               3                   17
29   17               1                   20
30   17               2                   18
⋮    ⋮                ⋮                   ⋮
4971 14               3                   18
4972 17               3                   12
4973 17               1                   20
4974 17               3                   14
4975 17               3                   16
4976 17               2                   18
4977 17               3                   21
4978 17               1                   21
4979 17               3                   18
4980 17               2                   21
4981 16               3                   21
4982 17               3                   11
4983 17               3                    8
4984 17               3                   17
4985 17               3                   17
4986 17               1                   17
4987 17               3                   14
4988 17               2                   15
4989 17               3                   21
4990 17               3                   16
4991 17               2                   19
4992 17               1                   18
4993 17               2                   15
4994 17               1                   21
4995 17               3                    9
4996 17               3                   20
4997 17               3                   16
4998 17               2                   18
4999 17               3                   18
5000 17               3                   19

En natuurlijk kun je ook dit bestand weer opslaan.

In [ ]:
write_sav(spss, "studenteninspss.sav")

# XML-bestanden
Ook XML-data kun je met R inlezen en bewerken. Je gebruikt daarbij het [XML2](https://xml2.r-lib.org/://)-package:

In [ ]:
install.packages("xml2")
library(xml2)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Daarnaast halen we met een GET-commando informatie van een website. Voor het GET-commando heb je het [httr](https://cran.r-project.org/web/packages/httr/vignettes/quickstart.html)-package nodig:

In [ ]:
install.packages("httr")
library(httr)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

We gaan XML-data lezen van de wikipedia-pagina van [Hadley Wickham](https://en.wikipedia.org/wiki/Hadley_Wickham) (de auteur van ons fijne R-boek). We controleren ook eerst even of de data die we ophalen van het XML-formaat is:

In [ ]:
url <- "https://en.wikipedia.org/w/api.php?action=query&titles=Hadley%20Wickham&prop=revisions&rvprop=timestamp%7Cuser%7Ccomment%7Ccontent&rvlimit=5&format=xml&rvdir=newer&rvstart=2015-01-14T17%3A12%3A45Z&rvsection=0"

# Get XML revision history
resp_xml <- GET(url)

# Check response is XML 
http_type(resp_xml)

[1] "text/xml"

Data-formaat klopt, kunnen we nu de revisie-data (= wie heeft er wanneer aan deze pagina gezeten) gaan inlezen:

In [ ]:
# Examine returned text with content()
rev_text <- content(resp_xml, as="text")

# Turn rev_text into an XML document
rev_xml <- read_xml(rev_text)

# Examine the structure of rev_xml
xml_structure(rev_xml)

<api>
  <continue [rvcontinue, continue]>
  <warnings>
    <main [space]>
      {text}
    <revisions [space]>
      {text}
  <query>
    <pages>
      <page [_idx, pageid, ns, title]>
        <revisions>
          <rev [user, anon, timestamp, contentformat, contentmodel, comment, space]>
            {text}
          <rev [user, anon, timestamp, contentformat, contentmodel, comment, space]>
            {text}
          <rev [user, timestamp, contentformat, contentmodel, comment, space]>
            {text}
          <rev [user, timestamp, contentformat, contentmodel, comment, space]>
            {text}
          <rev [user, timestamp, contentformat, contentmodel, comment, space]>
            {text}

We zien nu de structuur van de data, maar nog niet de data zelf:

In [ ]:
# Find all nodes using XPATH "/api/query/pages/page/revisions/rev"
xml_find_all(rev_xml, "/api/query/pages/page/revisions/rev")

{xml_nodeset (5)}
[1] <rev user="214.28.226.251" anon="" timestamp="2015-01-14T17:12:45Z" conte ...
[2] <rev user="73.183.151.193" anon="" timestamp="2015-01-15T15:49:34Z" conte ...
[3] <rev user="FeanorStar7" timestamp="2015-01-24T16:34:31Z" contentformat="t ...
[4] <rev user="KasparBot" timestamp="2015-04-26T19:18:17Z" contentformat="tex ...
[5] <rev user="Spkal" timestamp="2015-05-06T18:24:57Z" contentformat="text/x- ...

Bovenstaand zie je de (eerste) 5 users die de pagina gewijzigd hebben (tussen 14 januari 2015 en 6 mei 2015).

Als je de tekst van de wikipedia-pagina wilt zien, gebruik je xml_text. Je ziet de tekst 5x, want er zijn 5 ' nodes' gevonden:

In [ ]:
# Find all rev nodes anywhere in document
rev_nodes <- xml_find_all(rev_xml, "//rev")
# Use xml_text() to get text from rev_nodes
xml_text(rev_nodes)

[1] "'''Hadley Mary Helen Wickham III''' is a  [[statistician]] from [[New Zealand]] who is currently Chief Scientist at [[RStudio]]<ref>{{cite web|url=http://washstat.org/wss1310.shtml |title=Washington Statistical Society October 2013 Newsletter |publisher=Washstat.org |date= |accessdate=2014-02-12}}</ref><ref>{{cite web|url=http://news.idg.no/cw/art.cfm?id=F66B12BB-D13E-94B0-DAA22F5AB01BEFE7 |title=60+ R resources to improve your data skills ( - Software ) |publisher=News.idg.no |date= |accessdate=2014-02-12}}</ref> and an [[Professors_in_the_United_States#Adjunct_professor|adjunct]] [[Assistant Professor]] of statistics at [[Rice University]].<ref name=\"about\">{{cite web|url=http://www.rstudio.com/about/ |title=About - RStudio |accessdate=2014-08-13}}</ref> He is best known for his development of open-source statistical analysis software packages for [[R (programming language)]] that implement logics of [[data visualisation]] and data transformation. Wickham completed his undergraduate studies at the [[University of Auckland]] and his PhD at [[Iowa State University]] under the supervision of Di Cook and Heike Hoffman.<ref>{{cite web|URL=http://blog.revolutionanalytics.com/2010/09/the-r-files-hadley-wickham.html |title= The R-Files: Hadley Wickham}}</ref> In 2006 he was awarded the [[John_Chambers_(statistician)|John Chambers]] Award for Statistical Computing for his work developing tools for data reshaping and visualisation.<ref>{{cite web|url=http://stat-computing.org/awards/jmc/winners.html |title=John Chambers Award Past winners|publisher=ASA Sections on Statistical Computing, Statistical Graphics,|date= |accessdate=2014-08-12}}</ref>\n\nHe is a prominent and active member of the [[R (programming language)|R]] user community and has developed several notable and widely used packages including [[ggplot2]], plyr, dplyr, and reshape2.<ref name=\"about\" /><ref>{{cite web|url=http://www.r-statistics.com/2013/06/top-100-r-packages-for-2013-jan-may/ |title=Top 100 R Packages for 2013 (Jan-May)! |publisher=R-statistics blog |date= |accessdate=2014-08-12}}</ref>"
[2] "'''Hadley Wickham''' is a  [[statistician]] from [[New Zealand]] who is currently Chief Scientist at [[RStudio]]<ref>{{cite web|url=http://washstat.org/wss1310.shtml |title=Washington Statistical Society October 2013 Newsletter |publisher=Washstat.org |date= |accessdate=2014-02-12}}</ref><ref>{{cite web|url=http://news.idg.no/cw/art.cfm?id=F66B12BB-D13E-94B0-DAA22F5AB01BEFE7 |title=60+ R resources to improve your data skills ( - Software ) |publisher=News.idg.no |date= |accessdate=2014-02-12}}</ref> and an [[Professors_in_the_United_States#Adjunct_professor|adjunct]] [[Assistant Professor]] of statistics at [[Rice University]].<ref name=\"about\">{{cite web|url=http://www.rstudio.com/about/ |title=About - RStudio |accessdate=2014-08-13}}</ref> He is best known for his development of open-source statistical analysis software packages for [[R (programming language)]] that implement logics of [[data visualisation]] and data transformation. Wickham completed his undergraduate studies at the [[University of Auckland]] and his PhD at [[Iowa State University]] under the supervision of Di Cook and Heike Hoffman.<ref>{{cite web|URL=http://blog.revolutionanalytics.com/2010/09/the-r-files-hadley-wickham.html |title= The R-Files: Hadley Wickham}}</ref> In 2006 he was awarded the [[John_Chambers_(statistician)|John Chambers]] Award for Statistical Computing for his work developing tools for data reshaping and visualisation.<ref>{{cite web|url=http://stat-computing.org/awards/jmc/winners.html |title=John Chambers Award Past winners|publisher=ASA Sections on Statistical Computing, Statistical Graphics,|date= |accessdate=2014-08-12}}</ref>\n\nHe is a prominent and active member of the [[R (programming language)|R]] user community and has developed several notable and widely used packages including [[ggplot2]], plyr, dplyr, and reshape2.<ref name=\"about\" /><ref>{{cite web|url=http://www.r-statistics.com/2013/06/top-100-r-packages-for-2013-jan-may/ |title=Top 100 R Packages for 2013 (Jan-May)! |publisher=R-statistics blog |date= |accessdate=2014-08-12}}</ref>"
[3] "'''Hadley Wickham''' is a  [[statistician]] from [[New Zealand]] who is currently Chief Scientist at [[RStudio]]<ref>{{cite web|url=http://washstat.org/wss1310.shtml |title=Washington Statistical Society October 2013 Newsletter |publisher=Washstat.org |date= |accessdate=2014-02-12}}</ref><ref>{{cite web|url=http://news.idg.no/cw/art.cfm?id=F66B12BB-D13E-94B0-DAA22F5AB01BEFE7 |title=60+ R resources to improve your data skills ( - Software ) |publisher=News.idg.no |date= |accessdate=2014-02-12}}</ref> and an [[Professors_in_the_United_States#Adjunct_professor|adjunct]] [[Assistant Professor]] of statistics at [[Rice University]].<ref name=\"about\">{{cite web|url=http://www.rstudio.com/about/ |title=About - RStudio |accessdate=2014-08-13}}</ref> He is best known for his development of open-source statistical analysis software packages for [[R (programming language)]] that implement logics of [[data visualisation]] and data transformation. Wickham completed his undergraduate studies at the [[University of Auckland]] and his PhD at [[Iowa State University]] under the supervision of Di Cook and Heike Hoffman.<ref>{{cite web|URL=http://blog.revolutionanalytics.com/2010/09/the-r-files-hadley-wickham.html |title= The R-Files: Hadley Wickham}}</ref> In 2006 he was awarded the [[John_Chambers_(statistician)|John Chambers]] Award for Statistical Computing for his work developing tools for data reshaping and visualisation.<ref>{{cite web|url=http://stat-computing.org/awards/jmc/winners.html |title=John Chambers Award Past winners|publisher=ASA Sections on Statistical Computing, Statistical Graphics,|date= |accessdate=2014-08-12}}</ref>\n\nHe is a prominent and active member of the [[R (programming language)|R]] user community and has developed several notable and widely used packages including [[ggplot2]], plyr, dplyr, and reshape2.<ref name=\"about\" /><ref>{{cite web|url=http://www.r-statistics.com/2013/06/top-100-r-packages-for-2013-jan-may/ |title=Top 100 R Packages for 2013 (Jan-May)! |publisher=R-statistics blog |date= |accessdate=2014-08-12}}</ref>"
[4] "'''Hadley Wickham''' is a  [[statistician]] from [[New Zealand]] who is currently Chief Scientist at [[RStudio]]<ref>{{cite web|url=http://washstat.org/wss1310.shtml |title=Washington Statistical Society October 2013 Newsletter |publisher=Washstat.org |date= |accessdate=2014-02-12}}</ref><ref>{{cite web|url=http://news.idg.no/cw/art.cfm?id=F66B12BB-D13E-94B0-DAA22F5AB01BEFE7 |title=60+ R resources to improve your data skills ( - Software ) |publisher=News.idg.no |date= |accessdate=2014-02-12}}</ref> and an [[Professors_in_the_United_States#Adjunct_professor|adjunct]] [[Assistant Professor]] of statistics at [[Rice University]].<ref name=\"about\">{{cite web|url=http://www.rstudio.com/about/ |title=About - RStudio |accessdate=2014-08-13}}</ref> He is best known for his development of open-source statistical analysis software packages for [[R (programming language)]] that implement logics of [[data visualisation]] and data transformation. Wickham completed his undergraduate studies at the [[University of Auckland]] and his PhD at [[Iowa State University]] under the supervision of Di Cook and Heike Hoffman.<ref>{{cite web|URL=http://blog.revolutionanalytics.com/2010/09/the-r-files-hadley-wickham.html |title= The R-Files: Hadley Wickham}}</ref> In 2006 he was awarded the [[John_Chambers_(statistician)|John Chambers]] Award for Statistical Computing for his work developing tools for data reshaping and visualisation.<ref>{{cite web|url=http://stat-computing.org/awards/jmc/winners.html |title=John Chambers Award Past winners|publisher=ASA Sections on Statistical Computing, Statistical Graphics,|date= |accessdate=2014-08-12}}</ref>\n\nHe is a prominent and active member of the [[R (programming language)|R]] user community and has developed several notable and widely used packages including [[ggplot2]], plyr, dplyr, and reshape2.<ref name=\"about\" /><ref>{{cite web|url=http://www.r-statistics.com/2013/06/top-100-r-packages-for-2013-jan-may/ |title=Top 100 R Packages for 2013 (Jan-May)! |publisher=R-statistics blog |date= |accessdate=2014-08-12}}</ref>"
[5] "'''Hadley Wickham''' is a  [[statistician]] from [[New Zealand]] who is currently Chief Scientist at [[RStudio]]<ref>{{cite web|url=http://washstat.org/wss1310.shtml |title=Washington Statistical Society October 2013 Newsletter |publisher=Washstat.org |date= |accessdate=2014-02-12}}</ref><ref>{{cite web|url=http://news.idg.no/cw/art.cfm?id=F66B12BB-D13E-94B0-DAA22F5AB01BEFE7 |title=60+ R resources to improve your data skills ( - Software ) |publisher=News.idg.no |date= |accessdate=2014-02-12}}</ref> and an [[Professors_in_the_United_States#Adjunct_professor|adjunct]] [[Assistant Professor]] of statistics at [[Rice University]].<ref name=\"about\">{{cite web|url=http://www.rstudio.com/about/ |title=About - RStudio |accessdate=2014-08-13}}</ref> He is best known for his development of open-source statistical analysis software packages for [[R (programming language)]] that implement logics of [[data visualisation]] and data transformation. Wickham completed his undergraduate studies at the [[University of Auckland]] and his PhD at [[Iowa State University]] under the supervision of Di Cook and Heike Hoffman.<ref>{{cite web|URL=http://blog.revolutionanalytics.com/2010/09/the-r-files-hadley-wickham.html |title= The R-Files: Hadley Wickham}}</ref> In 2006 he was awarded the [[John_Chambers_(statistician)|John Chambers]] Award for Statistical Computing for his work developing tools for data reshaping and visualisation.<ref>{{cite web|url=http://stat-computing.org/awards/jmc/winners.html |title=John Chambers Award Past winners|publisher=ASA Sections on Statistical Computing, Statistical Graphics,|date= |accessdate=2014-08-12}}</ref>\n\nHe is a prominent and active member of the [[R (programming language)|R]] user community and has developed several notable and widely used packages including [[ggplot2]], plyr, dplyr, and reshape2.<ref name=\"about\" /><ref>{{cite web|url=http://www.r-statistics.com/2013/06/top-100-r-packages-for-2013-jan-may/ |title=Top 100 R Packages for 2013 (Jan-May)! |publisher=R-statistics blog |date= |accessdate=2014-08-12}}</ref>"

Als je wat meer informatie wilt, bijvoorbeeld over de eerste user die de pagina gewijzigd heeft, gebruik je xml_attrs() and xml_attr():

In [ ]:
# The first rev node
first_rev_node <- xml_find_first(rev_xml, "//rev")

# Find all attributes with xml_attrs()
xml_attrs(first_rev_node)

                  user                   anon              timestamp
      "214.28.226.251"                     "" "2015-01-14T17:12:45Z"
         contentformat           contentmodel                comment
         "text/x-wiki"             "wikitext"                     ""
                 space
            "preserve"

We kunnen ook de userid's van alle 5 personen die een wijziging hebben gemaakt, laten zien:

In [ ]:
# Find user attribute for all rev nodes
xml_attr(rev_nodes, "user")

[1] "214.28.226.251" "73.183.151.193" "FeanorStar7"    "KasparBot"
[5] "Spkal"

Kunnen we een functie maken die alle bovenstaande acties in 1x doet?<br>
Jazeker:

In [ ]:
get_revision_history <- function(article_title){
  # Get raw revision response
  rev_resp <- resp_xml
  
  # Turn the content() of rev_resp into XML
  rev_xml <- read_xml(content(rev_resp, "text"))
  
  # Find revision nodes
  rev_nodes <- xml_find_all(rev_xml, "//rev")

  # Parse out usernames
  user <- xml_attr(rev_nodes, "user")
  
  # Parse out timestamps
  timestamp <- readr::parse_datetime(xml_attr(rev_nodes, "timestamp"))
  
  # Parse out content
  content <- xml_text(rev_nodes)
  
  # Return data frame 
  data.frame(user = user,
    timestamp = timestamp,
    content = substr(content, 1, 40))
}

Even kijken of ie werkt:

In [ ]:
# Call function for "Hadley Wickham"
get_revision_history(article_title = "Hadley Wickham")

  user           timestamp           content
1 214.28.226.251 2015-01-14 17:12:45 '''Hadley Mary Helen Wickham III''' is a
2 73.183.151.193 2015-01-15 15:49:34 '''Hadley Wickham''' is a  [[statisticia
3 FeanorStar7    2015-01-24 16:34:31 '''Hadley Wickham''' is a  [[statisticia
4 KasparBot      2015-04-26 19:18:17 '''Hadley Wickham''' is a  [[statisticia
5 Spkal          2015-05-06 18:24:57 '''Hadley Wickham''' is a  [[statisticia

Werkt ie ook voor andere pagina's?

In [ ]:
get_revision_history(article_title = "Elon Musk")

  user           timestamp           content
1 214.28.226.251 2015-01-14 17:12:45 '''Hadley Mary Helen Wickham III''' is a
2 73.183.151.193 2015-01-15 15:49:34 '''Hadley Wickham''' is a  [[statisticia
3 FeanorStar7    2015-01-24 16:34:31 '''Hadley Wickham''' is a  [[statisticia
4 KasparBot      2015-04-26 19:18:17 '''Hadley Wickham''' is a  [[statisticia
5 Spkal          2015-05-06 18:24:57 '''Hadley Wickham''' is a  [[statisticia

Zo niet! Je zult eerst de URL (zie boven) moeten aanpassen:

In [ ]:
url <- "https://en.wikipedia.org/w/api.php?action=query&titles=Elon%20Musk&prop=revisions&rvprop=timestamp%7Cuser%7Ccomment%7Ccontent&rvlimit=10&format=xml&rvdir=newer&rvstart=2015-01-14T17%3A12%3A45Z&rvsection=0"
resp_xml <- GET(url)

Nog eens proberen (met 5 'extra' gebruikers):

In [ ]:
get_revision_history(article_title = "Elon Musk")

   user          timestamp           content
1  209.250.173.7 2015-01-15 18:29:56 {{Use mdy dates|date=October 2014}}\n{{In
2  IronGargoyle  2015-01-15 18:30:16 {{Use mdy dates|date=October 2014}}\n{{In
3  50.68.16.34   2015-01-16 08:10:39 {{Use mdy dates|date=October 2014}}\n{{In
4  50.100.177.24 2015-01-17 01:55:55 {{Use mdy dates|date=October 2014}}\n{{In
5  50.100.177.24 2015-01-17 01:56:59 {{Use mdy dates|date=October 2014}}\n{{In
6  50.100.177.24 2015-01-17 01:59:02 {{Use mdy dates|date=October 2014}}\n{{In
7  50.100.177.24 2015-01-17 01:59:49 {{Use mdy dates|date=October 2014}}\n{{In
8  50.100.177.24 2015-01-17 02:00:56 \n{{Use mdy dates|date=October 2014}}\n{{I
9  50.100.177.24 2015-01-17 02:01:23 \n{{Use mdy dates|date=October 2014}}\n{{I
10 50.100.177.24 2015-01-17 02:01:53 \n{{Use mdy dates|date=October 2014}}\n{{I

Even pingen: is 50.100.177.24 van de Grote Elon??? Waarschijnlijk toch niet .. ;)

NB: bovenstaand XML-voorbeeld is met veel dank overgenomen van:<br>
https://rpubs.com/Sergio_Garcia/working_with_web_data_in_r