In [1]:
install.packages("tidyverse")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [2]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [3]:
table4a

  country     1999   2000
1 Afghanistan    745   2666
2 Brazil       37737  80488
3 China       212258 213766

In [4]:
table4a %>%
  gather('1999','2000',key="year", value="cases")

  country     year cases
1 Afghanistan 1999    745
2 Brazil      1999  37737
3 China       1999 212258
4 Afghanistan 2000   2666
5 Brazil      2000  80488
6 China       2000 213766

In [5]:
table4a %>%
  pivot_longer(c(`1999`, `2000`), names_to = "year", values_to = "cases")

  country     year cases
1 Afghanistan 1999    745
2 Afghanistan 2000   2666
3 Brazil      1999  37737
4 Brazil      2000  80488
5 China       1999 212258
6 China       2000 213766

In [6]:
table2

   country     year type       count
1  Afghanistan 1999 cases             745
2  Afghanistan 1999 population   19987071
3  Afghanistan 2000 cases            2666
4  Afghanistan 2000 population   20595360
5  Brazil      1999 cases           37737
6  Brazil      1999 population  172006362
7  Brazil      2000 cases           80488
8  Brazil      2000 population  174504898
9  China       1999 cases          212258
10 China       1999 population 1272915272
11 China       2000 cases          213766
12 China       2000 population 1280428583

In [7]:
spread(table2,key=type, value=count)

  country     year cases  population
1 Afghanistan 1999    745   19987071
2 Afghanistan 2000   2666   20595360
3 Brazil      1999  37737  172006362
4 Brazil      2000  80488  174504898
5 China       1999 212258 1272915272
6 China       2000 213766 1280428583

In [8]:
table3

  country     year rate
1 Afghanistan 1999 745/19987071
2 Afghanistan 2000 2666/20595360
3 Brazil      1999 37737/172006362
4 Brazil      2000 80488/174504898
5 China       1999 212258/1272915272
6 China       2000 213766/1280428583

In [9]:
table3 %>%
  separate(rate, into = c("cases", "population"), sep="/")

  country     year cases  population
1 Afghanistan 1999 745    19987071
2 Afghanistan 2000 2666   20595360
3 Brazil      1999 37737  172006362
4 Brazil      2000 80488  174504898
5 China       1999 212258 1272915272
6 China       2000 213766 1280428583

In [10]:
table3 %>%
  separate(rate, into = c("cases", "population"), sep="/", convert=TRUE)

  country     year cases  population
1 Afghanistan 1999    745   19987071
2 Afghanistan 2000   2666   20595360
3 Brazil      1999  37737  172006362
4 Brazil      2000  80488  174504898
5 China       1999 212258 1272915272
6 China       2000 213766 1280428583

In [11]:
table3 %>%
  separate(year, into = c("century", "year"), sep = 2)

  country     century year rate
1 Afghanistan 19      99   745/19987071
2 Afghanistan 20      00   2666/20595360
3 Brazil      19      99   37737/172006362
4 Brazil      20      00   80488/174504898
5 China       19      99   212258/1272915272
6 China       20      00   213766/1280428583

In [12]:
table5 %>%
  unite(new, century, year)

  country     new   rate
1 Afghanistan 19_99 745/19987071
2 Afghanistan 20_00 2666/20595360
3 Brazil      19_99 37737/172006362
4 Brazil      20_00 80488/174504898
5 China       19_99 212258/1272915272
6 China       20_00 213766/1280428583

In [13]:
table5 %>%
  unite(new, century, year, sep = "")

  country     new  rate
1 Afghanistan 1999 745/19987071
2 Afghanistan 2000 2666/20595360
3 Brazil      1999 37737/172006362
4 Brazil      2000 80488/174504898
5 China       1999 212258/1272915272
6 China       2000 213766/1280428583

In [14]:
who

     country     iso2 iso3 year new_sp_m014 new_sp_m1524 new_sp_m2534
1    Afghanistan AF   AFG  1980  NA          NA           NA
2    Afghanistan AF   AFG  1981  NA          NA           NA
3    Afghanistan AF   AFG  1982  NA          NA           NA
4    Afghanistan AF   AFG  1983  NA          NA           NA
5    Afghanistan AF   AFG  1984  NA          NA           NA
6    Afghanistan AF   AFG  1985  NA          NA           NA
7    Afghanistan AF   AFG  1986  NA          NA           NA
8    Afghanistan AF   AFG  1987  NA          NA           NA
9    Afghanistan AF   AFG  1988  NA          NA           NA
10   Afghanistan AF   AFG  1989  NA          NA           NA
11   Afghanistan AF   AFG  1990  NA          NA           NA
12   Afghanistan AF   AFG  1991  NA          NA           NA
13   Afghanistan AF   AFG  1992  NA          NA           NA
14   Afghanistan AF   AFG  1993  NA          NA           NA
15   Afghanistan AF   AFG  1994  NA          NA           NA
16   Afghanistan AF   AFG  1995  NA          NA           NA
17   Afghanistan AF   AFG  1996  NA          NA           NA
18   Afghanistan AF   AFG  1997   0          10            6
19   Afghanistan AF   AFG  1998  30         129          128
20   Afghanistan AF   AFG  1999   8          55           55
21   Afghanistan AF   AFG  2000  52         228          183
22   Afghanistan AF   AFG  2001 129         379          349
23   Afghanistan AF   AFG  2002  90         476          481
24   Afghanistan AF   AFG  2003 127         511          436
25   Afghanistan AF   AFG  2004 139         537          568
26   Afghanistan AF   AFG  2005 151         606          560
27   Afghanistan AF   AFG  2006 193         837          791
28   Afghanistan AF   AFG  2007 186         856          840
29   Afghanistan AF   AFG  2008 187         941          773
30   Afghanistan AF   AFG  2009 200         906          705
⋮    ⋮           ⋮    ⋮    ⋮    ⋮           ⋮            ⋮
7211 Zimbabwe    ZW   ZWE  1984  NA          NA            NA
7212 Zimbabwe    ZW   ZWE  1985  NA          NA            NA
7213 Zimbabwe    ZW   ZWE  1986  NA          NA            NA
7214 Zimbabwe    ZW   ZWE  1987  NA          NA            NA
7215 Zimbabwe    ZW   ZWE  1988  NA          NA            NA
7216 Zimbabwe    ZW   ZWE  1989  NA          NA            NA
7217 Zimbabwe    ZW   ZWE  1990  NA          NA            NA
7218 Zimbabwe    ZW   ZWE  1991  NA          NA            NA
7219 Zimbabwe    ZW   ZWE  1992  NA          NA            NA
7220 Zimbabwe    ZW   ZWE  1993  NA          NA            NA
7221 Zimbabwe    ZW   ZWE  1994  NA          NA            NA
7222 Zimbabwe    ZW   ZWE  1995  NA          NA            NA
7223 Zimbabwe    ZW   ZWE  1996  NA          NA            NA
7224 Zimbabwe    ZW   ZWE  1997  NA          NA            NA
7225 Zimbabwe    ZW   ZWE  1998  NA          NA            NA
7226 Zimbabwe    ZW   ZWE  1999  NA          NA            NA
7227 Zimbabwe    ZW   ZWE  2000  NA          NA            NA
7228 Zimbabwe    ZW   ZWE  2001  NA          NA            NA
7229 Zimbabwe    ZW   ZWE  2002 191         600          2548
7230 Zimbabwe    ZW   ZWE  2003 133         874          3048
7231 Zimbabwe    ZW   ZWE  2004 187         833          2908
7232 Zimbabwe    ZW   ZWE  2005 210         837          2264
7233 Zimbabwe    ZW   ZWE  2006 215         736          2391
7234 Zimbabwe    ZW   ZWE  2007 138         500          3693
7235 Zimbabwe    ZW   ZWE  2008 127         614             0
7236 Zimbabwe    ZW   ZWE  2009 125         578            NA
7237 Zimbabwe    ZW   ZWE  2010 150         710          2208
7238 Zimbabwe    ZW   ZWE  2011 152         784          2467
7239 Zimbabwe    ZW   ZWE  2012 120         783          2421
7240 Zimbabwe    ZW   ZWE  2013  NA          NA            NA
     new_sp_m3544 new_sp_m4554 new_sp_m5564 ⋯ newrel_m4554 newrel_m5564
1     NA           NA           NA          ⋯ NA           NA
2     NA           NA           NA          ⋯ NA           NA
3     NA           NA           NA          ⋯ NA           NA
4     NA           NA           NA          ⋯ NA           NA
5     NA           NA           NA          ⋯ NA           NA
6     NA           NA           NA          ⋯ NA           NA
7     NA           NA           NA          ⋯ NA           NA
8     NA           NA           NA          ⋯ NA           NA
9     NA           NA           NA          ⋯ NA           NA
10    NA           NA           NA          ⋯ NA           NA
11    NA           NA           NA          ⋯ NA           NA
12    NA           NA           NA          ⋯ NA           NA
13    NA           NA           NA          ⋯ NA           NA
14    NA           NA           NA          ⋯ NA           NA
15    NA           NA           NA          ⋯ NA           NA
16    NA           NA           NA          ⋯ NA           NA
17    NA           NA           NA          ⋯ NA           NA
18     3            5            2          ⋯ NA           NA
19    90           89           64          ⋯ NA           NA
20    47           34           21          ⋯ NA           NA
21   149          129           94          ⋯ NA           NA
22   274          204          139          ⋯ NA           NA
23   368          246          241          ⋯ NA           NA
24   284          256          288          ⋯ NA           NA
25   360          358          386          ⋯ NA           NA
26   472          453          470          ⋯ NA           NA
27   574          572          572          ⋯ NA           NA
28   597          566          630          ⋯ NA           NA
29   545          570          630          ⋯ NA           NA
30   499          491          596          ⋯ NA           NA
⋮    ⋮            ⋮            ⋮            ⋱ ⋮            ⋮
7211   NA           NA          NA          ⋯   NA           NA
7212   NA           NA          NA          ⋯   NA           NA
7213   NA           NA          NA          ⋯   NA           NA
7214   NA           NA          NA          ⋯   NA           NA
7215   NA           NA          NA          ⋯   NA           NA
7216   NA           NA          NA          ⋯   NA           NA
7217   NA           NA          NA          ⋯   NA           NA
7218   NA           NA          NA          ⋯   NA           NA
7219   NA           NA          NA          ⋯   NA           NA
7220   NA           NA          NA          ⋯   NA           NA
7221   NA           NA          NA          ⋯   NA           NA
7222   NA           NA          NA          ⋯   NA           NA
7223   NA           NA          NA          ⋯   NA           NA
7224   NA           NA          NA          ⋯   NA           NA
7225   NA           NA          NA          ⋯   NA           NA
7226   NA           NA          NA          ⋯   NA           NA
7227   NA           NA          NA          ⋯   NA           NA
7228   NA           NA          NA          ⋯   NA           NA
7229 1662          744         315          ⋯   NA           NA
7230 2228          981         367          ⋯   NA           NA
7231 2298         1056         366          ⋯   NA           NA
7232 1855          762         295          ⋯   NA           NA
7233 1939          896         348          ⋯   NA           NA
7234    0          716         292          ⋯   NA           NA
7235 3316          704         263          ⋯   NA           NA
7236 3471          681         293          ⋯   NA           NA
7237 1682          761         350          ⋯   NA           NA
7238 2071          780         377          ⋯   NA           NA
7239 2086          796         360          ⋯   NA           NA
7240   NA           NA          NA          ⋯ 2349         1206
     newrel_m65 newrel_f014 newrel_f1524 newrel_f2534 newrel_f3544 newrel_f4554
1    NA         NA          NA           NA           NA           NA
2    NA         NA          NA           NA           NA           NA
3    NA         NA          NA           NA           NA           NA
4    NA         NA          NA           NA           NA           NA
5    NA         NA          NA           NA           NA           NA
6    NA         NA          NA           NA           NA           NA
7    NA         NA          NA           NA           NA           NA
8    NA         NA          NA           NA           NA           NA
9    NA         NA          NA           NA           NA           NA
10   NA         NA          NA           NA           NA           NA
11   NA         NA          NA           NA           NA           NA
12   NA         NA          NA           NA           NA           NA
13   NA         NA          NA           NA           NA           NA
14   NA         NA          NA           NA           NA           NA
15   NA         NA          NA           NA           NA           NA
16   NA         NA          NA           NA           NA           NA
17   NA         NA          NA           NA           NA           NA
18   NA         NA          NA           NA           NA           NA
19   NA         NA          NA           NA           NA           NA
20   NA         NA          NA           NA           NA           NA
21   NA         NA          NA           NA           NA           NA
22   NA         NA          NA           NA           NA           NA
23   NA         NA          NA           NA           NA           NA
24   NA         NA          NA           NA           NA           NA
25   NA         NA          NA           NA           NA           NA
26   NA         NA          NA           NA           NA           NA
27   NA         NA          NA           NA           NA           NA
28   NA         NA          NA           NA           NA           NA
29   NA         NA          NA           NA           NA           NA
30   NA         NA          NA           NA           NA           NA
⋮    ⋮          ⋮           ⋮            ⋮            ⋮            ⋮
7211   NA         NA          NA           NA           NA           NA
7212   NA         NA          NA           NA           NA           NA
7213   NA         NA          NA           NA           NA           NA
7214   NA         NA          NA           NA           NA           NA
7215   NA         NA          NA           NA           NA           NA
7216   NA         NA          NA           NA           NA           NA
7217   NA         NA          NA           NA           NA           NA
7218   NA         NA          NA           NA           NA           NA
7219   NA         NA          NA           NA           NA           NA
7220   NA         NA          NA           NA           NA           NA
7221   NA         NA          NA           NA           NA           NA
7222   NA         NA          NA           NA           NA           NA
7223   NA         NA          NA           NA           NA           NA
7224   NA         NA          NA           NA           NA           NA
7225   NA         NA          NA           NA           NA           NA
7226   NA         NA          NA           NA           NA           NA
7227   NA         NA          NA           NA           NA           NA
7228   NA         NA          NA           NA           NA           NA
7229   NA         NA          NA           NA           NA           NA
7230   NA         NA          NA           NA           NA           NA
7231   NA         NA          NA           NA           NA           NA
7232   NA         NA          NA           NA           NA           NA
7233   NA         NA          NA           NA           NA           NA
7234   NA         NA          NA           NA           NA           NA
7235   NA         NA          NA           NA           NA           NA
7236   NA         NA          NA           NA           NA           NA
7237   NA         NA          NA           NA           NA           NA
7238   NA         NA          NA           NA           NA           NA
7239   NA         NA          NA           NA           NA           NA
7240 1208       1252        2069         4649         3526         1453
     newrel_f5564 newrel_f65
1    NA           NA
2    NA           NA
3    NA           NA
4    NA           NA
5    NA           NA
6    NA           NA
7    NA           NA
8    NA           NA
9    NA           NA
10   NA           NA
11   NA           NA
12   NA           NA
13   NA           NA
14   NA           NA
15   NA           NA
16   NA           NA
17   NA           NA
18   NA           NA
19   NA           NA
20   NA           NA
21   NA           NA
22   NA           NA
23   NA           NA
24   NA           NA
25   NA           NA
26   NA           NA
27   NA           NA
28   NA           NA
29   NA           NA
30   NA           NA
⋮    ⋮            ⋮
7211  NA           NA
7212  NA           NA
7213  NA           NA
7214  NA           NA
7215  NA           NA
7216  NA           NA
7217  NA           NA
7218  NA           NA
7219  NA           NA
7220  NA           NA
7221  NA           NA
7222  NA           NA
7223  NA           NA
7224  NA           NA
7225  NA           NA
7226  NA           NA
7227  NA           NA
7228  NA           NA
7229  NA           NA
7230  NA           NA
7231  NA           NA
7232  NA           NA
7233  NA           NA
7234  NA           NA
7235  NA           NA
7236  NA           NA
7237  NA           NA
7238  NA           NA
7239  NA           NA
7240 811          725

In [15]:
?who

In [16]:
who1 <- who %>%
  pivot_longer(
    cols = new_sp_m014:newrel_f65,
    names_to = "key",
    values_to = "cases",
    values_drop_na = TRUE
  )

In [17]:
who1

      country     iso2 iso3 year key          cases
1     Afghanistan AF   AFG  1997 new_sp_m014    0
2     Afghanistan AF   AFG  1997 new_sp_m1524  10
3     Afghanistan AF   AFG  1997 new_sp_m2534   6
4     Afghanistan AF   AFG  1997 new_sp_m3544   3
5     Afghanistan AF   AFG  1997 new_sp_m4554   5
6     Afghanistan AF   AFG  1997 new_sp_m5564   2
7     Afghanistan AF   AFG  1997 new_sp_m65     0
8     Afghanistan AF   AFG  1997 new_sp_f014    5
9     Afghanistan AF   AFG  1997 new_sp_f1524  38
10    Afghanistan AF   AFG  1997 new_sp_f2534  36
11    Afghanistan AF   AFG  1997 new_sp_f3544  14
12    Afghanistan AF   AFG  1997 new_sp_f4554   8
13    Afghanistan AF   AFG  1997 new_sp_f5564   0
14    Afghanistan AF   AFG  1997 new_sp_f65     1
15    Afghanistan AF   AFG  1998 new_sp_m014   30
16    Afghanistan AF   AFG  1998 new_sp_m1524 129
17    Afghanistan AF   AFG  1998 new_sp_m2534 128
18    Afghanistan AF   AFG  1998 new_sp_m3544  90
19    Afghanistan AF   AFG  1998 new_sp_m4554  89
20    Afghanistan AF   AFG  1998 new_sp_m5564  64
21    Afghanistan AF   AFG  1998 new_sp_m65    41
22    Afghanistan AF   AFG  1998 new_sp_f014   45
23    Afghanistan AF   AFG  1998 new_sp_f1524 350
24    Afghanistan AF   AFG  1998 new_sp_f2534 419
25    Afghanistan AF   AFG  1998 new_sp_f3544 194
26    Afghanistan AF   AFG  1998 new_sp_f4554 118
27    Afghanistan AF   AFG  1998 new_sp_f5564  61
28    Afghanistan AF   AFG  1998 new_sp_f65    20
29    Afghanistan AF   AFG  1999 new_sp_m014    8
30    Afghanistan AF   AFG  1999 new_sp_m1524  55
⋮     ⋮           ⋮    ⋮    ⋮    ⋮            ⋮
76017 Zimbabwe    ZW   ZWE  2012 new_sn_f5564  516
76018 Zimbabwe    ZW   ZWE  2012 new_sn_f65    432
76019 Zimbabwe    ZW   ZWE  2012 new_ep_m014   233
76020 Zimbabwe    ZW   ZWE  2012 new_ep_m1524  214
76021 Zimbabwe    ZW   ZWE  2012 new_ep_m2534  658
76022 Zimbabwe    ZW   ZWE  2012 new_ep_m3544  789
76023 Zimbabwe    ZW   ZWE  2012 new_ep_m4554  331
76024 Zimbabwe    ZW   ZWE  2012 new_ep_m5564  178
76025 Zimbabwe    ZW   ZWE  2012 new_ep_m65    182
76026 Zimbabwe    ZW   ZWE  2012 new_ep_f014   208
76027 Zimbabwe    ZW   ZWE  2012 new_ep_f1524  319
76028 Zimbabwe    ZW   ZWE  2012 new_ep_f2534  710
76029 Zimbabwe    ZW   ZWE  2012 new_ep_f3544  579
76030 Zimbabwe    ZW   ZWE  2012 new_ep_f4554  228
76031 Zimbabwe    ZW   ZWE  2012 new_ep_f5564  140
76032 Zimbabwe    ZW   ZWE  2012 new_ep_f65    143
76033 Zimbabwe    ZW   ZWE  2013 newrel_m014  1315
76034 Zimbabwe    ZW   ZWE  2013 newrel_m1524 1642
76035 Zimbabwe    ZW   ZWE  2013 newrel_m2534 5331
76036 Zimbabwe    ZW   ZWE  2013 newrel_m3544 5363
76037 Zimbabwe    ZW   ZWE  2013 newrel_m4554 2349
76038 Zimbabwe    ZW   ZWE  2013 newrel_m5564 1206
76039 Zimbabwe    ZW   ZWE  2013 newrel_m65   1208
76040 Zimbabwe    ZW   ZWE  2013 newrel_f014  1252
76041 Zimbabwe    ZW   ZWE  2013 newrel_f1524 2069
76042 Zimbabwe    ZW   ZWE  2013 newrel_f2534 4649
76043 Zimbabwe    ZW   ZWE  2013 newrel_f3544 3526
76044 Zimbabwe    ZW   ZWE  2013 newrel_f4554 1453
76045 Zimbabwe    ZW   ZWE  2013 newrel_f5564  811
76046 Zimbabwe    ZW   ZWE  2013 newrel_f65    725

In [18]:
who2 <- who1 %>%
  mutate(key = stringr::str_replace(key, "newrel", "new_rel"))
who2

      country     iso2 iso3 year key           cases
1     Afghanistan AF   AFG  1997 new_sp_m014     0
2     Afghanistan AF   AFG  1997 new_sp_m1524   10
3     Afghanistan AF   AFG  1997 new_sp_m2534    6
4     Afghanistan AF   AFG  1997 new_sp_m3544    3
5     Afghanistan AF   AFG  1997 new_sp_m4554    5
6     Afghanistan AF   AFG  1997 new_sp_m5564    2
7     Afghanistan AF   AFG  1997 new_sp_m65      0
8     Afghanistan AF   AFG  1997 new_sp_f014     5
9     Afghanistan AF   AFG  1997 new_sp_f1524   38
10    Afghanistan AF   AFG  1997 new_sp_f2534   36
11    Afghanistan AF   AFG  1997 new_sp_f3544   14
12    Afghanistan AF   AFG  1997 new_sp_f4554    8
13    Afghanistan AF   AFG  1997 new_sp_f5564    0
14    Afghanistan AF   AFG  1997 new_sp_f65      1
15    Afghanistan AF   AFG  1998 new_sp_m014    30
16    Afghanistan AF   AFG  1998 new_sp_m1524  129
17    Afghanistan AF   AFG  1998 new_sp_m2534  128
18    Afghanistan AF   AFG  1998 new_sp_m3544   90
19    Afghanistan AF   AFG  1998 new_sp_m4554   89
20    Afghanistan AF   AFG  1998 new_sp_m5564   64
21    Afghanistan AF   AFG  1998 new_sp_m65     41
22    Afghanistan AF   AFG  1998 new_sp_f014    45
23    Afghanistan AF   AFG  1998 new_sp_f1524  350
24    Afghanistan AF   AFG  1998 new_sp_f2534  419
25    Afghanistan AF   AFG  1998 new_sp_f3544  194
26    Afghanistan AF   AFG  1998 new_sp_f4554  118
27    Afghanistan AF   AFG  1998 new_sp_f5564   61
28    Afghanistan AF   AFG  1998 new_sp_f65     20
29    Afghanistan AF   AFG  1999 new_sp_m014     8
30    Afghanistan AF   AFG  1999 new_sp_m1524   55
⋮     ⋮           ⋮    ⋮    ⋮    ⋮             ⋮
76017 Zimbabwe    ZW   ZWE  2012 new_sn_f5564   516
76018 Zimbabwe    ZW   ZWE  2012 new_sn_f65     432
76019 Zimbabwe    ZW   ZWE  2012 new_ep_m014    233
76020 Zimbabwe    ZW   ZWE  2012 new_ep_m1524   214
76021 Zimbabwe    ZW   ZWE  2012 new_ep_m2534   658
76022 Zimbabwe    ZW   ZWE  2012 new_ep_m3544   789
76023 Zimbabwe    ZW   ZWE  2012 new_ep_m4554   331
76024 Zimbabwe    ZW   ZWE  2012 new_ep_m5564   178
76025 Zimbabwe    ZW   ZWE  2012 new_ep_m65     182
76026 Zimbabwe    ZW   ZWE  2012 new_ep_f014    208
76027 Zimbabwe    ZW   ZWE  2012 new_ep_f1524   319
76028 Zimbabwe    ZW   ZWE  2012 new_ep_f2534   710
76029 Zimbabwe    ZW   ZWE  2012 new_ep_f3544   579
76030 Zimbabwe    ZW   ZWE  2012 new_ep_f4554   228
76031 Zimbabwe    ZW   ZWE  2012 new_ep_f5564   140
76032 Zimbabwe    ZW   ZWE  2012 new_ep_f65     143
76033 Zimbabwe    ZW   ZWE  2013 new_rel_m014  1315
76034 Zimbabwe    ZW   ZWE  2013 new_rel_m1524 1642
76035 Zimbabwe    ZW   ZWE  2013 new_rel_m2534 5331
76036 Zimbabwe    ZW   ZWE  2013 new_rel_m3544 5363
76037 Zimbabwe    ZW   ZWE  2013 new_rel_m4554 2349
76038 Zimbabwe    ZW   ZWE  2013 new_rel_m5564 1206
76039 Zimbabwe    ZW   ZWE  2013 new_rel_m65   1208
76040 Zimbabwe    ZW   ZWE  2013 new_rel_f014  1252
76041 Zimbabwe    ZW   ZWE  2013 new_rel_f1524 2069
76042 Zimbabwe    ZW   ZWE  2013 new_rel_f2534 4649
76043 Zimbabwe    ZW   ZWE  2013 new_rel_f3544 3526
76044 Zimbabwe    ZW   ZWE  2013 new_rel_f4554 1453
76045 Zimbabwe    ZW   ZWE  2013 new_rel_f5564  811
76046 Zimbabwe    ZW   ZWE  2013 new_rel_f65    725

In [19]:
who3 <- who2 %>%
  separate(key, c("new", "type", "sexage"), sep = "_")
who3

      country     iso2 iso3 year new type sexage cases
1     Afghanistan AF   AFG  1997 new sp   m014     0
2     Afghanistan AF   AFG  1997 new sp   m1524   10
3     Afghanistan AF   AFG  1997 new sp   m2534    6
4     Afghanistan AF   AFG  1997 new sp   m3544    3
5     Afghanistan AF   AFG  1997 new sp   m4554    5
6     Afghanistan AF   AFG  1997 new sp   m5564    2
7     Afghanistan AF   AFG  1997 new sp   m65      0
8     Afghanistan AF   AFG  1997 new sp   f014     5
9     Afghanistan AF   AFG  1997 new sp   f1524   38
10    Afghanistan AF   AFG  1997 new sp   f2534   36
11    Afghanistan AF   AFG  1997 new sp   f3544   14
12    Afghanistan AF   AFG  1997 new sp   f4554    8
13    Afghanistan AF   AFG  1997 new sp   f5564    0
14    Afghanistan AF   AFG  1997 new sp   f65      1
15    Afghanistan AF   AFG  1998 new sp   m014    30
16    Afghanistan AF   AFG  1998 new sp   m1524  129
17    Afghanistan AF   AFG  1998 new sp   m2534  128
18    Afghanistan AF   AFG  1998 new sp   m3544   90
19    Afghanistan AF   AFG  1998 new sp   m4554   89
20    Afghanistan AF   AFG  1998 new sp   m5564   64
21    Afghanistan AF   AFG  1998 new sp   m65     41
22    Afghanistan AF   AFG  1998 new sp   f014    45
23    Afghanistan AF   AFG  1998 new sp   f1524  350
24    Afghanistan AF   AFG  1998 new sp   f2534  419
25    Afghanistan AF   AFG  1998 new sp   f3544  194
26    Afghanistan AF   AFG  1998 new sp   f4554  118
27    Afghanistan AF   AFG  1998 new sp   f5564   61
28    Afghanistan AF   AFG  1998 new sp   f65     20
29    Afghanistan AF   AFG  1999 new sp   m014     8
30    Afghanistan AF   AFG  1999 new sp   m1524   55
⋮     ⋮           ⋮    ⋮    ⋮    ⋮   ⋮    ⋮      ⋮
76017 Zimbabwe    ZW   ZWE  2012 new sn   f5564   516
76018 Zimbabwe    ZW   ZWE  2012 new sn   f65     432
76019 Zimbabwe    ZW   ZWE  2012 new ep   m014    233
76020 Zimbabwe    ZW   ZWE  2012 new ep   m1524   214
76021 Zimbabwe    ZW   ZWE  2012 new ep   m2534   658
76022 Zimbabwe    ZW   ZWE  2012 new ep   m3544   789
76023 Zimbabwe    ZW   ZWE  2012 new ep   m4554   331
76024 Zimbabwe    ZW   ZWE  2012 new ep   m5564   178
76025 Zimbabwe    ZW   ZWE  2012 new ep   m65     182
76026 Zimbabwe    ZW   ZWE  2012 new ep   f014    208
76027 Zimbabwe    ZW   ZWE  2012 new ep   f1524   319
76028 Zimbabwe    ZW   ZWE  2012 new ep   f2534   710
76029 Zimbabwe    ZW   ZWE  2012 new ep   f3544   579
76030 Zimbabwe    ZW   ZWE  2012 new ep   f4554   228
76031 Zimbabwe    ZW   ZWE  2012 new ep   f5564   140
76032 Zimbabwe    ZW   ZWE  2012 new ep   f65     143
76033 Zimbabwe    ZW   ZWE  2013 new rel  m014   1315
76034 Zimbabwe    ZW   ZWE  2013 new rel  m1524  1642
76035 Zimbabwe    ZW   ZWE  2013 new rel  m2534  5331
76036 Zimbabwe    ZW   ZWE  2013 new rel  m3544  5363
76037 Zimbabwe    ZW   ZWE  2013 new rel  m4554  2349
76038 Zimbabwe    ZW   ZWE  2013 new rel  m5564  1206
76039 Zimbabwe    ZW   ZWE  2013 new rel  m65    1208
76040 Zimbabwe    ZW   ZWE  2013 new rel  f014   1252
76041 Zimbabwe    ZW   ZWE  2013 new rel  f1524  2069
76042 Zimbabwe    ZW   ZWE  2013 new rel  f2534  4649
76043 Zimbabwe    ZW   ZWE  2013 new rel  f3544  3526
76044 Zimbabwe    ZW   ZWE  2013 new rel  f4554  1453
76045 Zimbabwe    ZW   ZWE  2013 new rel  f5564   811
76046 Zimbabwe    ZW   ZWE  2013 new rel  f65     725

In [20]:
who4 <- who3 %>%
  select(-new, -iso2, -iso3)
who4

      country     year type sexage cases
1     Afghanistan 1997 sp   m014     0
2     Afghanistan 1997 sp   m1524   10
3     Afghanistan 1997 sp   m2534    6
4     Afghanistan 1997 sp   m3544    3
5     Afghanistan 1997 sp   m4554    5
6     Afghanistan 1997 sp   m5564    2
7     Afghanistan 1997 sp   m65      0
8     Afghanistan 1997 sp   f014     5
9     Afghanistan 1997 sp   f1524   38
10    Afghanistan 1997 sp   f2534   36
11    Afghanistan 1997 sp   f3544   14
12    Afghanistan 1997 sp   f4554    8
13    Afghanistan 1997 sp   f5564    0
14    Afghanistan 1997 sp   f65      1
15    Afghanistan 1998 sp   m014    30
16    Afghanistan 1998 sp   m1524  129
17    Afghanistan 1998 sp   m2534  128
18    Afghanistan 1998 sp   m3544   90
19    Afghanistan 1998 sp   m4554   89
20    Afghanistan 1998 sp   m5564   64
21    Afghanistan 1998 sp   m65     41
22    Afghanistan 1998 sp   f014    45
23    Afghanistan 1998 sp   f1524  350
24    Afghanistan 1998 sp   f2534  419
25    Afghanistan 1998 sp   f3544  194
26    Afghanistan 1998 sp   f4554  118
27    Afghanistan 1998 sp   f5564   61
28    Afghanistan 1998 sp   f65     20
29    Afghanistan 1999 sp   m014     8
30    Afghanistan 1999 sp   m1524   55
⋮     ⋮           ⋮    ⋮    ⋮      ⋮
76017 Zimbabwe    2012 sn   f5564   516
76018 Zimbabwe    2012 sn   f65     432
76019 Zimbabwe    2012 ep   m014    233
76020 Zimbabwe    2012 ep   m1524   214
76021 Zimbabwe    2012 ep   m2534   658
76022 Zimbabwe    2012 ep   m3544   789
76023 Zimbabwe    2012 ep   m4554   331
76024 Zimbabwe    2012 ep   m5564   178
76025 Zimbabwe    2012 ep   m65     182
76026 Zimbabwe    2012 ep   f014    208
76027 Zimbabwe    2012 ep   f1524   319
76028 Zimbabwe    2012 ep   f2534   710
76029 Zimbabwe    2012 ep   f3544   579
76030 Zimbabwe    2012 ep   f4554   228
76031 Zimbabwe    2012 ep   f5564   140
76032 Zimbabwe    2012 ep   f65     143
76033 Zimbabwe    2013 rel  m014   1315
76034 Zimbabwe    2013 rel  m1524  1642
76035 Zimbabwe    2013 rel  m2534  5331
76036 Zimbabwe    2013 rel  m3544  5363
76037 Zimbabwe    2013 rel  m4554  2349
76038 Zimbabwe    2013 rel  m5564  1206
76039 Zimbabwe    2013 rel  m65    1208
76040 Zimbabwe    2013 rel  f014   1252
76041 Zimbabwe    2013 rel  f1524  2069
76042 Zimbabwe    2013 rel  f2534  4649
76043 Zimbabwe    2013 rel  f3544  3526
76044 Zimbabwe    2013 rel  f4554  1453
76045 Zimbabwe    2013 rel  f5564   811
76046 Zimbabwe    2013 rel  f65     725

In [21]:
who5 <- who4 %>%
  separate(sexage, c("sex", "age"), sep = 1)
who5

      country     year type sex age  cases
1     Afghanistan 1997 sp   m   014    0
2     Afghanistan 1997 sp   m   1524  10
3     Afghanistan 1997 sp   m   2534   6
4     Afghanistan 1997 sp   m   3544   3
5     Afghanistan 1997 sp   m   4554   5
6     Afghanistan 1997 sp   m   5564   2
7     Afghanistan 1997 sp   m   65     0
8     Afghanistan 1997 sp   f   014    5
9     Afghanistan 1997 sp   f   1524  38
10    Afghanistan 1997 sp   f   2534  36
11    Afghanistan 1997 sp   f   3544  14
12    Afghanistan 1997 sp   f   4554   8
13    Afghanistan 1997 sp   f   5564   0
14    Afghanistan 1997 sp   f   65     1
15    Afghanistan 1998 sp   m   014   30
16    Afghanistan 1998 sp   m   1524 129
17    Afghanistan 1998 sp   m   2534 128
18    Afghanistan 1998 sp   m   3544  90
19    Afghanistan 1998 sp   m   4554  89
20    Afghanistan 1998 sp   m   5564  64
21    Afghanistan 1998 sp   m   65    41
22    Afghanistan 1998 sp   f   014   45
23    Afghanistan 1998 sp   f   1524 350
24    Afghanistan 1998 sp   f   2534 419
25    Afghanistan 1998 sp   f   3544 194
26    Afghanistan 1998 sp   f   4554 118
27    Afghanistan 1998 sp   f   5564  61
28    Afghanistan 1998 sp   f   65    20
29    Afghanistan 1999 sp   m   014    8
30    Afghanistan 1999 sp   m   1524  55
⋮     ⋮           ⋮    ⋮    ⋮   ⋮    ⋮
76017 Zimbabwe    2012 sn   f   5564  516
76018 Zimbabwe    2012 sn   f   65    432
76019 Zimbabwe    2012 ep   m   014   233
76020 Zimbabwe    2012 ep   m   1524  214
76021 Zimbabwe    2012 ep   m   2534  658
76022 Zimbabwe    2012 ep   m   3544  789
76023 Zimbabwe    2012 ep   m   4554  331
76024 Zimbabwe    2012 ep   m   5564  178
76025 Zimbabwe    2012 ep   m   65    182
76026 Zimbabwe    2012 ep   f   014   208
76027 Zimbabwe    2012 ep   f   1524  319
76028 Zimbabwe    2012 ep   f   2534  710
76029 Zimbabwe    2012 ep   f   3544  579
76030 Zimbabwe    2012 ep   f   4554  228
76031 Zimbabwe    2012 ep   f   5564  140
76032 Zimbabwe    2012 ep   f   65    143
76033 Zimbabwe    2013 rel  m   014  1315
76034 Zimbabwe    2013 rel  m   1524 1642
76035 Zimbabwe    2013 rel  m   2534 5331
76036 Zimbabwe    2013 rel  m   3544 5363
76037 Zimbabwe    2013 rel  m   4554 2349
76038 Zimbabwe    2013 rel  m   5564 1206
76039 Zimbabwe    2013 rel  m   65   1208
76040 Zimbabwe    2013 rel  f   014  1252
76041 Zimbabwe    2013 rel  f   1524 2069
76042 Zimbabwe    2013 rel  f   2534 4649
76043 Zimbabwe    2013 rel  f   3544 3526
76044 Zimbabwe    2013 rel  f   4554 1453
76045 Zimbabwe    2013 rel  f   5564  811
76046 Zimbabwe    2013 rel  f   65    725